---
title: "\"Sunn\" kommuneøkonomi fase 2 - Tønsberg kommune"
date: 2025-05-24
categories: ["Økonomi", "Kommune", "Kutt", "Sunn kommuneøkonomi", "Tønsberg kommune", "velferd"]
description: "Nå kommer neste bølge med kutt fra prosjektet \"'Sunn' kommuneøkonomi\". Under har jeg samlet alt av sakspapirer som ligger til…"
page-layout: article
toc: false
reading-time: true
title-block-banner: false
date-format: "D. MMMM YYYY"
---
:::: {.post-body}
```{=html}
<p>Nå kommer neste bølge med kutt fra prosjektet "'Sunn' kommuneøkonomi". Under har jeg samlet alt av sakspapirer som ligger til behandling i kommunens råd og utvalg den nærmeste tiden. All tekst er fra selve saksfremlegget og vedleggene finnes under overskriften "Vedlegg".</p>
```

```{=html}
<p>Del denne posten i håp om at flest mulig blir gjort kjent med det økonomiske uføre Tønsberg kommune nå er i, og de enorme kuttene som vil ramme de svakeste sterkt!</p>
```

```{=html}
<p>Innholdsfortegnelse</p>
```

```{=html}
<p>– Sunn kommuneøkonomi fase 2 (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#sunn-kommuneokonomi-fase-2)</p>
```

```{=html}
<p>– Kommunedirektørens innstilling (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#kommunedirektorens-innstilling)</p>
```

```{=html}
<p>– Sammendrag: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#sammendrag)</p>
```

```{=html}
<p>– Vedlegg: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#vedlegg)</p>
```

```{=html}
<p>– Faktagrunnlag: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#faktagrunnlag)</p>
```

```{=html}
<p>– Kompetansekartlegging og bemanningsplanlegging (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#kompetansekartlegging-og-bemanningsplanlegging)</p>
```

```{=html}
<p>– Under arbeid / nye tiltak som foreslås utredet: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#under-arbeid-nye-tiltak-som-foreslas-utredet)</p>
```

```{=html}
<p>– Liste over «ikke lovpålagte» tjenester (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#liste-over-ikke-lovpalagte-tjenester)</p>
```

```{=html}
<p>– Lånegarantier: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#lanegarantier)</p>
```

```{=html}
<p>– Gjennomgang av planlagte investeringer (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#gjennomgang-av-planlagte-investeringer)</p>
```

```{=html}
<p>– Rettslig grunnlag (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#rettslig-grunnlag)</p>
```

```{=html}
<p>– Forholdet til kommuneplanen (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#forholdet-til-kommuneplanen)</p>
```

```{=html}
<p>– Vurderinger: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#vurderinger)</p>
```

```{=html}
<p>– Nærmere om grepene for framskyndet innsparing i 2025: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#naermere-om-grepene-for-framskyndet-innsparing-i-2025)</p>
```

```{=html}
<p>– Redusere eksisterende rammer basert på mindreforbruk i driften i 2024 – totalt 25 mill. kroner (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#redusere-eksisterende-rammer-basert-pa-mindreforbruk-i-driften-i-2024-totalt-25-mill-kroner)</p>
```

```{=html}
<p>– Ansatte arrangementer, kaffetrekk - 1,7 mill. kroner (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#ansatte-arrangementer-kaffetrekk-1-7-mill-kroner)</p>
```

```{=html}
<p>– Framskynde innsparingskravet per rammeområde – totalt 33,1 mill. kroner (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#framskynde-innsparingskravet-per-rammeomrade-totalt-33-1-mill-kroner)</p>
```

```{=html}
<p>– Innsparingspotensial framover (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#innsparingspotensial-framover)</p>
```

```{=html}
<p>– Dekningsgrad: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#dekningsgrad)</p>
```

```{=html}
<p>– Konsekvens for oppnåelse av FNs bærekraftmål: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#konsekvens-for-oppnaelse-av-fns-baerekraftmal)</p>
```

```{=html}
<p>– Effekt for klima: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#effekt-for-klima)</p>
```

```{=html}
<p>– Konsekvenser for barn og unge (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#konsekvenser-for-barn-og-unge)</p>
```

```{=html}
<p>– Alternative løsninger (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#alternative-losninger)</p>
```

```{=html}
<p>– Økonomiske konsekvenser (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#okonomiske-konsekvenser)</p>
```

```{=html}
<p>– Konklusjon (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#konklusjon)</p>
```

```{=html}
<p>– Videre behandling: (https://sondrestraume.wordpress.com/2025/05/24/sunn-kommuneokonomi-fase-2-tonsberg-kommune/#videre-behandling)</p>
```

```{=html}
<p>JournalpostID 25/56862</p>
```

```{=html}
<p>Saksbehandler:  Kristian Holberg Lægreid, telefon:  Økonomi og virksomhetsstyring</p>
```

## Sunn kommuneøkonomi fase 2

```{=html}
<p>Klikk på saksnummeret for å komme til saken i de ulike rådene og utvalgene hvor saken er oppe til behandling!</p>
```

```{=html}
<p>UtvalgMøtedatoTypeSaksnummerEldreråd02.06.2025PS039/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-747!SvrVEw/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-747!ozLEBx)Innvandrerutvalget02.06.2025PS024/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-755!nLjxO6/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-755!KNw8wc)Råd for personer med funksjonsnedsettelse02.06.2025PS042/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-739!i9pmWI/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-739!4ctU9y)Ungdomsrådet02.06.2025PS 031/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-771!KsSV4K/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-771!wc6u6c)Klima- og miljøutvalget02.06.2025PS039/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-763!CjUVl7/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-763!53z6Uz)Utvalg for mestring, helse og velferd03.06.2025PS041/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-779!l0mwFK/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-779!w4eXa2)Utvalg for kultur, idrett og folkehelse03.06.2025PS037/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-787!yfYZFA/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-787!sGHhJc)Utvalg for miljø, teknikk og næring04.06.2025PS039/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-795!oDcAvo/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-795!yiLPy0)Utvalg for oppvekst og opplæring04.06.2025PS035/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-803!uEqAst/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-803!7taIVm)Utvalg for plan og bygg06.06.2025PS068/25 (https://www.tonsberg.kommune.no/tjenester/innsyn/politisk-moteplan/#/details/m-8bdf57ba__d7af__4650__824e__88b9e98fe418-811!lXLfgO/d-8bdf57ba__d7af__4650__824e__88b9e98fe418-2022594232!m-811!d2CHC9)Administrasjonsutvalget PS Formannskapet PS Kommunestyret PS</p>
```

### Kommunedirektørens innstilling

```{=html}
<p>– Saken tas til orientering</p>
```

```{=html}
<p>– Innsparinger jfr. vedlegg «Oversikt innsparingstiltak 2025» vedtas</p>
```

```{=html}
<p>– Økonomiplanutvalget holdes løpende orientert om fremdriften i prosjekt «Sunn kommuneøkonomi»</p>
```

```{=html}
<p>– Følgende nye tiltak utredes nærmere:</p>
```

```{=html}
<p>– Innføring av eiendomsskatt</p>
```

```{=html}
<p>– Modell for refusjon ressurskrevende tjenester</p>
```

```{=html}
<p>– Dimensjonering av administrative ressurser og eventuelt justering av administrativ organisering</p>
```

```{=html}
<p>– Arealeffektivisering, salg og utnyttelse av kommunale eiendommer</p>
```

```{=html}
<p>– Ordningen med lånegarantier overfor lag og foreninger tas opp til ny vurdering.</p>
```

```{=html}
<p>– Administrasjonen arbeider videre med tiltak for perioden 2026–2028. Disse innarbeides i kommunedirektørens forslag til handlingsprogram 2026–2029 som vedtas i desember 2025. Dette inkluderer også en revurdering av fremdriftsplan tilknyttet planlagte investeringer i økonomiplanperioden.</p>
```

### Sammendrag:

```{=html}
<p>Regnskapsresultatet for 2024 ble betydelig svakere enn budsjettert. Svikt i skatteinngangen er den største enkeltårsaken. Sammen med et høyere driftsnivå enn sammenlignbare kommuner, bidrar dette til at kommunen må gjennomføre innsparingstiltak. En foreløpig prognose viser at kommunen også må forvente et lavere nivå på skatteinntektene i årene framover. Dette gjør det nødvendig å framskynde planlagte innsparinger som er vedtatt i handlingsprogrammet for 2025–28. Formelt må endringer i rammene gjøres av kommunestyret. Det legges opp til at budsjettendringene vedtas i behandlingen av perioderapport 1, jfr. egen sak.</p>
```

```{=html}
<p>Kommunedirektøren gir i denne saken en orientering om status i prosjektet «Sunn kommuneøkonomi» med konkrete innsparingsforslag for 2025, og en orientering om hvordan administrasjonen jobber for å bedre kommunens økonomi. Foreslåtte rammejusteringer i kommunens perioderapportering (P1) 2025 legger til grunn at foreslåtte tiltak i denne saken blir gjennomført.</p>
```

```{=html}
<p>Kommunedirektøren har det overordnede ansvaret for å sikre at kommunen er i stand til å levere lovpålagte og forsvarlige tjenester til innbyggerne. I møte med endringer i befolkningssammensetning, behov og økonomiske rammevilkår, er det kommunedirektørens oppgave å foreslå nødvendige tiltak som ivaretar kommunens økonomiske bærekraft. Dette innebærer å se på muligheten for både økte inntekter og reduserte kostnader. Det forestående omstillingsbehovet vil medføre justeringer i tjenestetilbudet, og målet er å sikre at kommunen fortsatt kan oppfylle sine forpliktelser innenfor de rammevilkårene kommunen har fått.</p>
```

```{=html}
<p>Økonomiplanutvalget har vært holdt orientert underveis.</p>
```

### Vedlegg:

```{=html}
<p>Vis tabell: Oversikt innsparingstiltak 2025 - Kommunedirektørens forslag til innsparingstiltak 2025 - Vedlegg 1 til sak Sunn kommuneøkonomi fase 2</p>
```

```{=html}
<p>Organisasjon og utvikling       2025       Merknad</p>
```

```{=html}
<p>Halvere kostnadene for erkjentlighetsarrangementet.       150       Se tiltakskort</p>
```

```{=html}
<p>Halvere gavebeløp til ansatte som slutter etter 10 års ans.       90       Se tiltakskort</p>
```

```{=html}
<p>Redusere nivå på lederutviklingsprogram       140       Se tiltakskort</p>
```

```{=html}
<p>Vakant stilling servicesenter       440</p>
```

```{=html}
<p>Diverse småkutt       100       Adgangskort, fastnummerserier</p>
```

```{=html}
<p>Økonomi og virksomhetsstyring</p>
```

```{=html}
<p>Redusert bemanning</p>
```

```{=html}
<p>Innsparing 80 pst. stilling - regnskap       579       Gjennomføres som følge av naturlig avgang og resultat av kompetanse og bemanningskartlegging</p>
```

```{=html}
<p>Samlet</p>
```

```{=html}
<p>Innsparing sykepengerefusjon       2 200       Basert på historisk merinntekt sykepengrefusjon 2023 og 2024</p>
```

```{=html}
<p>Redusert bemanning       540       Gjennomføres etter arbeidet med kompetansekartlegging og bemanningsplaner</p>
```

```{=html}
<p>Sum tiltak kom.dir, staber, folkevalgte       4 239</p>
```

```{=html}
<p>Gjenstående kom.dir., staber, folkevalgte       -100</p>
```

```{=html}
<p>Oppvekst og læring</p>
```

```{=html}
<p>ALLE - Flatt kutt fordelt på alle virksomheter       2 461       tatt ut fra 01.01.2025</p>
```

```{=html}
<p>ALLE - Innsparing sykepengerefusjon uten vikar settes inn       1 900       Basert på historisk merinntekt sykepengrefusjon 2023 og 2024</p>
```

```{=html}
<p>Flatt kutt i skolene       4 400       Skolene fordeler kuttet gjennom ressurstildelingsmodellen, langsiktig mål om å redusere ITu</p>
```

```{=html}
<p>Statsbudsjett - kompensasjon for endrede regler for kontantstøtte       2 000       Ikke disponert, barnehagene har fått budsjett for reelt barnetall</p>
```

```{=html}
<p>Bevilget av kommunestyret til skole/SFO       600       1500 ble bevilget kun for 2025, disponert vårhalvåret</p>
```

```{=html}
<p>Bevilget av kommunestyret til miljøterapeuter skole       300       Disponert vårhalvåret 2025</p>
```

```{=html}
<p>Oppvekststaben - bemanning       500       nedbemanning i stab, redusere individuell tirettelagt opplæring barnehage og private skoler samt grunnleggende norskopplæring</p>
```

```{=html}
<p>PPT       1 100       Redusere 1,7 årsverk i PPT og 0,3 årsverk i Logopedtjenesten</p>
```

```{=html}
<p>Barnevern, redusert bemanning       500       Redusere bemanning - Ikke identifisert</p>
```

```{=html}
<p>Barnevern, redusere ambulerende skolemiljøteam fra 6 til 4 stillinger       1 500       Redusere ambulerende skolemiljøteam fra 6 til 4 stillinger</p>
```

```{=html}
<p>Barn og unge       1 400       Vakante stillinger videreføres (1 psykolog+0,5 miljøterapeut)</p>
```

```{=html}
<p>Barnehager, nedleggelse Eik Vestre barnehage       400       Nedleggelse Eik Vestre barnehage, styrerstilling</p>
```

```{=html}
<p>Sum tiltak oppvekst og læring       17 061</p>
```

```{=html}
<p>Gjenstående oppvekst og læring       0</p>
```

```{=html}
<p>Mestring og helse</p>
```

```{=html}
<p>"Gjenbruk" smittevern (anslag)       1 500       Besparelser i vheter i hele kommunen, mest mestring og helse og barnehager- tas sentralt i M&H</p>
```

```{=html}
<p>Raskere kutt sykehjemsplasser       2 000       Fra opprinnelig nedtrekk i 2024</p>
```

```{=html}
<p>Flatt kutt/rammekutt i virksomhetene       5 800       Inndratte midler fra 2024</p>
```

```{=html}
<p>Reduksjon sykehjemsplasser       10 000       Orienteringssak 17 plasser (minus noe kostnader ved innsparing ØHD)</p>
```

```{=html}
<p>Flytting ØHD       500       Orienteringssak</p>
```

```{=html}
<p>Reduksjon nattevakter Åslyveien       900       2 årsverk (virksomheten beholder resternede beløp til kompanserende tiltak.</p>
```

```{=html}
<p>Sum tiltak mestring og helse       20 700</p>
```

```{=html}
<p>Gjenstående mestring og helse       -9 700</p>
```

```{=html}
<p>Kultur og samfunnsutvikling</p>
```

```{=html}
<p>Reduserte driftsposter 40100       556       redusert diverse driftsposter på ansvar 4100</p>
```

```{=html}
<p>Redusert ramme Læringssenteret       13 000       ramme redusert pr 030425</p>
```

```{=html}
<p>Redusert ramme NAV       7 000       ramme redusert pr 030425</p>
```

```{=html}
<p>Ekstra leieinntekt Bergsåsen idrettsanlegg       700       Ny avtale m Re vidg.skole</p>
```

```{=html}
<p>Redusere ant. dager åpent Ungdomsdrevet kafe No8       200       Holder da åpent 2 dg/uka</p>
```

```{=html}
<p>Reversere opptrapping utenforskap       1 000</p>
```

```{=html}
<p>Vakante stillinger bibliotek       340       Videreføre vakant stilling</p>
```

```{=html}
<p>Flatt kutt bibliotek       80</p>
```

```{=html}
<p>Vakant stilling Godt nok       900</p>
```

```{=html}
<p>Innsparing sykepengerefusjon       174       Basert på historisk merinntekt sykepengrefusjon 2023 og 2024, opprinnelig 1700</p>
```

```{=html}
<p>Sum tiltak kultur og samfunnsutvikling       23 950</p>
```

```{=html}
<p>Gjenstående kultur og samf.utvikl.       0</p>
```

```{=html}
<p>Plan, eiendom og teknikk</p>
```

```{=html}
<p>Flatt kutt By og stedsutvikling       550</p>
```

```{=html}
<p>økte parkeringsinntekter ved utvidelse av sentrumssone       800</p>
```

```{=html}
<p>Utsatt vedlikehold TKE og teknisk drift       2 200</p>
```

```{=html}
<p>Nedleggelse Eik Vestre bhg       200</p>
```

```{=html}
<p>økt ekstern prosjektfinansiering       300       Primært i BSU, Næring og kommunalteknikk</p>
```

```{=html}
<p>Innsparing sykepengerefusjon/ikke vikar       2 500</p>
```

```{=html}
<p>Sum tiltak plan, eiendom og teknikk       6 550</p>
```

```{=html}
<p>Gjenstående plan, eiendom og teknikk       0</p>
```

```{=html}
<p>Sum innsparingstiltak for å dekke uidentifiserte innsparingskrav i HP 25-28       72 500</p>
```

```{=html}
<p>Reversering av opptrappinger, vedtatt i HP 26-28       5 100</p>
```

```{=html}
<p>Konkrete tiltak vedtatt i HP 26-28       27 042</p>
```

```{=html}
<p>Egenandel kaffe ansatte       1 500</p>
```

```{=html}
<p>Sum alle tiltak       106 142</p>
```

```{=html}
<p>Gjenstående behov for innsparing uidentifiserte innsparingskrav       -9 800</p>
```

```{=html}
<p>Vis tabell: Oversikt innsparinger 2026-2028 - Arbeidsdokument innsparingstiltak 2026-2028 - Vedlegg 2 til sak Sunn kommuneøkonomi fase 2</p>
```

```{=html}
<p>Organisasjon og utvikling       2026       2027       2028       Merknad</p>
```

```{=html}
<p>Halvere kostnadene for erkjentlighetsarrangementet.       150       150       150</p>
```

```{=html}
<p>Halvere gavebeløp til ansatte som slutter etter 10 års ans.       90       90       90</p>
```

```{=html}
<p>Redusere nivå på lederutviklingsprogram       140       140       140       Bruke mer interne krefter</p>
```

```{=html}
<p>Vakant stilling servicesenter       440       440       440</p>
```

```{=html}
<p>Diverse småkutt       100       100       100       Adgangskort, fastnummerserier</p>
```

```{=html}
<p>Økonomi og virksomhetsstyring</p>
```

```{=html}
<p>Redusert bemanning</p>
```

```{=html}
<p>Innsparing 80 pst. stilling - regnskap       579       579       579       Noe av innsparingen benyttes til å dekke inn gjenstående innsparing fra tidligere år. Rest lagt her.</p>
```

```{=html}
<p>Samlet</p>
```

```{=html}
<p>Innsparing sykepengerefusjon       2 200       2 200       2 200       Basert på historisk merinntekt sykepengrefusjon 2023 og 2024</p>
```

```{=html}
<p>Redusert bemanning       540       1 000       1 500       Gjennomføres etter arbeidet med kompetansekartlegging og bemanningsplaner</p>
```

```{=html}
<p>Sum tiltak kom.dir, staber, folkevalgte       4 239       4 699       5 199</p>
```

```{=html}
<p>Oppvekst og læring</p>
```

```{=html}
<p>ALLE - Flatt kutt fordelt på alle virksomheter       2 461       2 461       2 461       tatt ut fra 01.01.2025</p>
```

```{=html}
<p>ALLE - Innsparing sykepengerefusjon uten vikar settes inn       1 900       1 900       1 900       Basert på historisk merinntekt sykepengrefusjon 2023 og 2024</p>
```

```{=html}
<p>Flatt kutt i skolene       10 200       15 200       20 700       Skolene fordeler kuttet gjennom ressurstildelingsmodellen, langsiktig mål om å redusere ITu</p>
```

```{=html}
<p>Statsbudsjett - kompensasjon for endrede regler for kontantstøtte       2 000       2 000       2 000       Ikke disponert, barnehagene har fått budsjett for reelt barnetall</p>
```

```{=html}
<p>Statsbudsjett - kompensasjon ny opplæringslov - ikke spesifisert       150       700       700       Ikke disponert</p>
```

```{=html}
<p>Bevilget av kommunestyret til skole/SFO</p>
```

```{=html}
<p>1500 ble bevilget kun for 2025, disponert vårhalvåret</p>
```

```{=html}
<p>Bevilget av kommunestyret til miljøterapeuter skole       800       800       800       Disponert vårhalvåret 2025</p>
```

```{=html}
<p>Oppvekststaben - bemanning       1 500       3 260       4 620       nedbemanning i stab, redusere individuell tirettelagt opplæring barnehage og private skoler samt grunnleggende norskopplæring</p>
```

```{=html}
<p>Oppvekststaben - reduksjon i overføring private barnehager</p>
```

```{=html}
<p>240       3 480</p>
```

```{=html}
<p>PPT       1 600       1 600       1 600       Redusere 1,7 årsverk i PPT og 0,3 årsverk i Logopedtjenesten</p>
```

```{=html}
<p>Barnevern, redusert bemanning       500       2 000       2 600       Redusere bemanning - Ikke identifisert</p>
```

```{=html}
<p>Barnevern, redusere ambulerende skolemiljøteam fra 6 til 4 stillinger       1 500       1 500       1 500       Redusere ambulerende skolemiljøteam fra 6 til 4 stillinger</p>
```

```{=html}
<p>Barn og unge</p>
```

```{=html}
<p>1 000       2 000       Redusere bemanning - Ikke identifisert</p>
```

```{=html}
<p>Barn og unge       1 400       1 400       1 400       Vakante stillinger videreføres (1 psykolog+0,5 miljøterapeut)</p>
```

```{=html}
<p>Barnehager, nedleggelse Eik Vestre barnehage       1 000       1 000       1 000       Nedleggelse Eik Vestre barnehage, styrerstilling</p>
```

```{=html}
<p>Barnehager       5 400       8 400       10 900       Redusere tiltaket "Økt grunnbemanning i barnehagene" (gir eogså effekt i 2029 og 2030)</p>
```

```{=html}
<p>Mulig nedleggelse Fon barnehage</p>
```

```{=html}
<p>Ny KST-sak i november 2025 - videreføre partsammensatt gruppe</p>
```

```{=html}
<p>Helsestasjon - redusere fra 3 til 2 eller 1</p>
```

```{=html}
<p>Vil trolig kreve investering - nedsette partsammensatt gruppe</p>
```

```{=html}
<p>Bygge ny barnehage på Sem og legge ned to små</p>
```

```{=html}
<p>Tiltaket vil kreve investering, men sjekke om kan gi gevinst - nedsette partsammensatt arbeidsgruppe</p>
```

```{=html}
<p>Endre budsjettfordeling for skolene</p>
```

```{=html}
<p>Tiltak som kan påvirke fordeling av skolenes flate kutt mer målrettet</p>
```

```{=html}
<p>Styrke systemer for tidlig identifisering for å redusere ITO</p>
```

```{=html}
<p>Tiltak under fordeling av skolenes kutt: tallfeste et måltall på nedrekk på antall årstimer til ITO omregnet til årsverk</p>
```

```{=html}
<p>Vurdere å kjøpe leide paviljonger i skolene (minus Vear U)</p>
```

```{=html}
<p>Tiltaket vil kreve investering, men sjekke om kan gi gevinst</p>
```

```{=html}
<p>Vurdere dimensjonering av merkantil ressurs i skolene</p>
```

```{=html}
<p>Tiltak under fordeling av skolenes kutt - nedsette partsammensatt arbeidsgruppe</p>
```

```{=html}
<p>Sum tiltak oppvekst og læring       30 411       43 461       57 661</p>
```

```{=html}
<p>Mestring og helse</p>
```

```{=html}
<p>"Gjenbruk" smittevern (anslag)</p>
```

```{=html}
<p>Besparelser i vheter i hele kommunen, mest mestring og helse og barnehager- tas sentralt i M&H</p>
```

```{=html}
<p>Raskere kutt sykehjemsplasser</p>
```

```{=html}
<p>Fra opprinnelig nedtrekk i 2024</p>
```

```{=html}
<p>Flatt kutt/rammekutt i virksomhetene       5 800       5 800       5 800       Inndratte midler fra 2024</p>
```

```{=html}
<p>Reduksjon sykehjemsplasser       20 000       20 000       20 000       Orienteringssak 17 plasser (minus noe kostnader ved innsparing ØHD)</p>
```

```{=html}
<p>Flytting ØHD       1 000       1 000       1 000       Orienteringssak</p>
```

```{=html}
<p>Flytting avlastningsbolig voksne       1 500       4 000       4 000       Egen sak</p>
```

```{=html}
<p>Reduksjon avlastningsbolig barn       2 000       2 000       2 000       Egen sak</p>
```

```{=html}
<p>Redusere nattevakter       10 000       10 000       10 000       ROS analyse pågår, frist 2605, tilsvarer 5 årsverk</p>
```

```{=html}
<p>Reduksjon nattevakter Åslyveien       1 800       1 800       1 800       2 årsverk (virksomheten beholder resternede beløp til kompanserende tiltak.</p>
```

```{=html}
<p>Fleksibelt avlastningstilbud</p>
```

```{=html}
<p>Orienteringssak i mai resten</p>
```

```{=html}
<p>Familieveiledning</p>
```

```{=html}
<p>Utredes videre</p>
```

```{=html}
<p>Ambulante tjenester PU</p>
```

```{=html}
<p>Utredes videre</p>
```

```{=html}
<p>Sykefraværsoppfølging</p>
```

```{=html}
<p>Egen sak juni, nye retningslinjer mm</p>
```

```{=html}
<p>Alarmsentral/responssenter</p>
```

```{=html}
<p>Utredes videre</p>
```

```{=html}
<p>Sum tiltak mestring og helse       42 100       44 600       44 600</p>
```

```{=html}
<p>Kultur og samfunnsutvikling</p>
```

```{=html}
<p>Reduserte driftsposter 40100       556       556       556       redusert diverse driftsposter på ansvar 4100</p>
```

```{=html}
<p>Redusert ramme Læringssenteret       13 000       13 000       13 000       ramme redusert pr 030425</p>
```

```{=html}
<p>Redusert ramme NAV       7 000       7 000       7 000       ramme redusert pr 030425</p>
```

```{=html}
<p>Ekstra leieinntekt Bergsåsen idrettsanlegg       700       700       700       Ny avtale m Re vidg.skole</p>
```

```{=html}
<p>Ikke annonsere 17. mai program i aviser       40       40       40</p>
```

```{=html}
<p>Redusere tilskudd org. med tilbud til voksne       650       650       650       Tilskudd voksenkorps opprettholdes</p>
```

```{=html}
<p>Endring markering middelalder og vikingtid       300       300       300       Egen sak</p>
```

```{=html}
<p>Si opp medlemskap i Oslofjordens Friluftsråd       230       230       230       1 års oppsigelsesfrist</p>
```

```{=html}
<p>Redusere åpningstid på fritidsklubber       900       900       900       Hver klubb åpen en ukedag. Ingen juniorklubber, 120% stilling</p>
```

```{=html}
<p>Redusere ant. dager åpent Ungdomsdrevet kafe No8       400       400       400       Holder da åpent 2 dg/uka</p>
```

```{=html}
<p>Reversere opptrapping utenforskap       1 000       1 000       1 000</p>
```

```{=html}
<p>Ikke delta i UKM       100       100       100</p>
```

```{=html}
<p>Reduksjon av kulturskoletilbudet</p>
```

```{=html}
<p>Under arbeid</p>
```

```{=html}
<p>Vakante stillinger bibliotek</p>
```

```{=html}
<p>Flatt kutt bibliotek       60       60       60</p>
```

```{=html}
<p>Redusert bemanning bibliotek</p>
```

```{=html}
<p>400       800</p>
```

```{=html}
<p>Redusert renhold bibliotek       150       300       300</p>
```

```{=html}
<p>Avvikle funksjon som skolebibliotekkoordinator       407       407       407</p>
```

```{=html}
<p>Vakant stilling Godt nok       900       900       900</p>
```

```{=html}
<p>Redusere overføringer til private og veledige org., Tbg livet mm       500       500       500       Til vurdering, ikke gjelder kulturtilskudd lag og foreninger</p>
```

```{=html}
<p>Avvikle tilskudd lag og foreninger, løyper og stier       210       210       210</p>
```

```{=html}
<p>Redusert bemanning</p>
```

```{=html}
<p>3 000       9 400</p>
```

```{=html}
<p>Innsparing sykepengerefusjon       174       174       174       Basert på historisk merinntekt sykepengrefusjon 2023 og 2024, opprinnelig 1700</p>
```

```{=html}
<p>Sum tiltak kultur og samfunnsutvikling       27 277       30 827       37 627</p>
```

```{=html}
<p>Plan, eiendom og teknikk</p>
```

```{=html}
<p>Flatt kutt By og stedsutvikling       550       550       550</p>
```

```{=html}
<p>Økte parkeringsinntekter ved utvidelse av sentrumssone       1 800       2 000       2 200</p>
```

```{=html}
<p>Tilskuddsordning klimatiltak foreninger       500       500       500</p>
```

```{=html}
<p>Økte festeinntekter       1 800       1 800       1 800</p>
```

```{=html}
<p>Utsatt vedlikehold TKE og teknisk drift</p>
```

```{=html}
<p>Forsterket vedlikehold TKE og teknisk drift       -2 400       -2 400       -1 600</p>
```

```{=html}
<p>Nedleggelse Eik Vestre bhg       400       400       400</p>
```

```{=html}
<p>Økt ekstern prosjektfinansiering       400       500       500       Primært i BSU, Næring og kommunalteknikk</p>
```

```{=html}
<p>Nedbemanning TKE       1 300       1 300       1 950</p>
```

```{=html}
<p>Lave gebyrinntekter ABL       -3 000</p>
```

```{=html}
<p>Nedbemanning /effektivisering ABL</p>
```

```{=html}
<p>1 000       2 000</p>
```

```{=html}
<p>Nedbemanning /effektivisering Teknisk drift       200       400       1 250</p>
```

```{=html}
<p>Innsparing sykepengerefusjon/ikke vikar       2 500       2 500       2 500</p>
```

```{=html}
<p>Sum tiltak plan, eiendom og teknikk       12 050       8 550       4 050</p>
```

```{=html}
<p>Sum innsparingstiltak for å dekke uidentifiserte innsparingskrav i HP 25-28       108 077       132 137       157 137</p>
```

```{=html}
<p>Reversering av opptrappinger, vedtatt i HP 26-28       5 100       5 100       5 100</p>
```

```{=html}
<p>Konkrete tiltak vedtatt i HP 26-28       34 500       34 500       34 500</p>
```

```{=html}
<p>Egenandel kaffe ansatte       2 300       2 300       2 300</p>
```

```{=html}
<p>Tiltak finans       5 443       19 646       39 776</p>
```

```{=html}
<p>Gjenværende uspesifiserte tiltak       1 211       28 802       47 600</p>
```

```{=html}
<p>Sum alle tiltak       156 631       222 485       286 413</p>
```

```{=html}
<p>Tiltakskort/ beskrivelse av større innsparingstiltak i 2025 og vurderte konsekvenser av disse 042-25_2 Tiltakskortbeskrivelse av st_rre innsparingstiltak i 2025 og vurderte konsekvenser av disse (https://sondrestraume.wordpress.com/wp-content/uploads/2025/05/042-25_2-tiltakskortbeskrivelse-av-st_rre-innsparingstiltak-i-2025-og-vurderte-konsekvenser-av-disse.pdf)Last ned (https://sondrestraume.wordpress.com/wp-content/uploads/2025/05/042-25_2-tiltakskortbeskrivelse-av-st_rre-innsparingstiltak-i-2025-og-vurderte-konsekvenser-av-disse.pdf)</p>
```

```{=html}
<p>Vis tabell: "Ikke lovpålagte" oppgaver og tjenester</p>
```

```{=html}
<p>Ikke lovpålagte oppgaver og tjenester       Kort beskrivelse av oppgaven/tjenesten       Netto utgift budsjett 2025 (1000 kr.)       Beskrivelse av mulig økonomisk effekt redusert utgift/økt inntekt eller bortfall av oppgaven/tjenest</p>
```

```{=html}
<p>Kommunedir, staber og folkevalgte</p>
```

```{=html}
<p>Erkjentlighetsarrangement og gaver       Feiring av 25 og 40årsjubilanter med festmiddag, gaver og blomster.       300       Foreslått halvert i Sunn kommuneøkonomi</p>
```

```{=html}
<p>Gave etter 10 års ansettelse       Gave, blomst og arrangement for ansatte som slutter etter 10 års amnsettelse       180       Ansatte som slutter etter mer enn 10 års ansettelse mottar en vase m verdi kr. 1800,-. Årlig bestilles 100 stk. Foreslås halvert i Sunn kommuneøkonomi</p>
```

```{=html}
<p>Kantine       Kantine på rådhuset. Mat til politiske møter og andre samlinger/ representasjonsoppdrag.       700       Et lokale det har blitt investert mye penger i, vil bli stående tomt. Mat og kaffe ved politiske møter og andre samlinger, må bestilles fra andre steder og kan forhøyeden utgiften. Et sosialt samlingspunkt på tvers, blir borte.</p>
```

```{=html}
<p>Forhåndsstemminger lørdager       Forhåndsstemmer er også tatt i mot på lørdager. Krever ekstra bemanning.       60       Det er lovpålagt å ta imot forhåndsstemmer, men ikke hvor mange steder og åpningstider.</p>
```

```{=html}
<p>Særskilt klagenemnd       Behandle klager for alle tjenesteområder som på bakgrunn av delegert myndighet gjør enkeltvedtak etter forvaltningslovens regler.       40       Klagenemndas oppgaver kan ivaretas av formannskapet - krever politisk behandling</p>
```

```{=html}
<p>Ordførers disp.kto inkludert TV-aksjonen       Benyttes til gaver, representasjon og tv-askjonen       200       149 000 brukt i 2024. Til representasjonsgaver</p>
```

```{=html}
<p>Hovedutvalg       Hovedutvalg er ikke lovpålagt - 488 `per hovedutvalg       2 440       Hovedutvalg er ikke lovpålagt - formannskap og kommunestyret kan i prinsippet vedta alt.Besparelse ved å kun ha 2 råd</p>
```

```{=html}
<p>Råd       Det er 3 lovpålagte medvirkningsråd, hvorav eldreråd og råd for personer med funksjonsnedsettelse er lovlig å slå sammen. Ungdomsråd er lovpålagt. Vi må altså ha 2 råd.       327</p>
```

```{=html}
<p>Kommunestyrerepr. utover lovkrav       Lovkravet i kommuneloven er 35 medl. for kommuner over 50000 innbyggere       605       Besparelse ved 35 repr. kontra dagens 43 medlemmer er 605`</p>
```

```{=html}
<p>Formannskapsrepr. utover lovkrav       Lovkravet i kommuneloven er at formannskapet skal ha min. 5 medlemmer. Tønsberg har i dag 11 medlemmer i formannskapet       321       Besparelse ved 5 repr. kontra dagens 11 repr. er 321`</p>
```

```{=html}
<p>Redusere antall medl. i hovedutvalg til 9       Det er i dag 11 medl. i hvert hovedutvalg, ingen lovkrav om hovedutvalg eller ant. medl.       369       Besparelse ved å gå ned til 9 medlemmer er 369`</p>
```

```{=html}
<p>Kommunestyret på dagtid       Ikke lovkrav om å ha politiske møter på dagtid       245       Besparelse ved å legge kommunestyret på kveldstid</p>
```

```{=html}
<p>Oppvekst og læring</p>
```

```{=html}
<p>Arbeidslivsfag for 10. klasse       Elevene får tilbud i de videregående skolene.       428       Alternativet til å kjøpe tilbudet i VGS er å organisere tilbudet ved våre egne ungdomsskoler. Tilbudet fremmer høy motivasjon hos elevene og vi vil kunne setilsvarende lav motivasjon om tilbudet organiseres på hjemskolen. Denne elevegruppen er sårbar med tanke på frafall fra videregående skole. Kostnaden pr elev idagens ordning er ca kr 10 000 pr år. Det er 140 elever som skal ha arbeidslivsfag på 10. trinn neste skoleår og disse forutsettes delt i 8 grupper om de er pånærskolen (regnet med 1 lærer + 1 assistent i alle timer). Besparelsen vil være forskjellen på 1 400 000 og 971 000 kroner. I tillegg vil kostnader til skoleskyss(busskort) kunne spares dersom elevene får tilbudet på nærskolen, men skolen vil også måtte investere noe mer i utstyr.</p>
```

```{=html}
<p>Beredskapsteam mot mobbing       Teamet skal bistå barn, foreldre, barnehager og skoler i tilfeller hvor ordinære tiltak for å forebygge eller håndtere mobbing ikke har ført fram eller ikke er iverksatt.       100       Det har vært en nedgang i henvendelser til teamet; 2022: 10, 2023: 5, 2024: 3. I samme periode har antallet henvendelser til mobbeombudet for Vestfold liggetmellom 12 og 15 saker pr år. Skolene har ved halvårlige "sjekkpunkter" mellom 40-50 pågående § 12-4 saker. Dersom beredskapteamet nedlegges, frigjøresarbeidskapasitet til andre oppgaver. Det kan være aktuelt å styre innsatsen til sakene hvor foreldre "klager" til lokal skolemyndighet og § 12-5-saker, hvor vi i dag harmanglende kapasitet og system - eller for å overta oppgaver etter stillinger som holdes vakante som følge av innsparingskrav. Elever, foreldre og skoler vil, etter hvatallene tyder på, ha tilnærmet lik ivaretakelse selv om teamet legges ned. Ressurser kan også styres mer mot forebyggende arbeid og ansatte kan overtaarbeidsoppgaver som holdes vakante som følge av kutt.</p>
```

```{=html}
<p>Elevrådskonferansen       Gjennomføres for elevrådene på mellomtrinnet og ungdomstrinnet annet hvert år.       120       Elevrådskonferansen er en møteplass for elevrådene fra alle offentlige og private skoler, hvor de arbeider med aktuelle temaer fra år til år. Ungdomstrinn ogmellomtrinn annet hvert år. Gjennomføres på lokalt hotell. Bortfall av konferansen betyr tap av en medvirkningsarena, men krav til medvirkning på den enkelte skole ilys av opplæringsloven er uforandret. Innsparingen her er bortfall av kostnad til hotell.</p>
```

```{=html}
<p>Ungt entreprenørskap       Ungt entreprenørskap har flere program fra 1.-10. trinn. En del skoler i Tønsberg deltar årlig. Kostnaden er en årskontigent.       200       Elevene og skolene mister et morsomt og spennende undervisningstilbud, som ofte er motiverende også for elever som opplever den "vanlige" skolehverdagen sommindre motiverende.</p>
```

```{=html}
<p>Geitmyra matkultursenter       Tverrfaglig mat og helse-tilbud for 6. trinn. Tilbudet medfører kostnad til kjøp av undervisningstjenester og skoleskyss.       2 400       Mat og helse-opplæringen kan ivaretas på egen skole. Kontrakten binder oss opp til 2028 + 4 års opsjon. Skoleskyss er inkludert.</p>
```

```{=html}
<p>Bakkeåsen skole       Bakkeåsen skole er et samarbeidsprosjekt mellom Tønsberg, Horten og Sandefjord kommuner. Tønsberg "eier" 5 elevplasser ved skolen og disse tildeles elever som har stort strev med å gå i ordinær hjemmeskole.       2 825       Bakkeåsen skole gir et godt tilbud til elever som har stort strev knyttet til det å gå i en ordinær hjemmeskole. Elevene har ofte omfattende enkeltvedtak og tilpasningeri skolehverdagen, og vil kreve dette også på en nærskole. Flere av elevene vil være svært aktuelle for plass i en kostnadskrevende alternativ opplæringsarena.Nettoutgiften som beskrives er kostnaden kommunen har til faste plasser i Bakkeåsen. Innsparing vil sannsynligvis være null ved oppsigelse av avtalen - eller så kankostnadene øke ved at kommunen må kjøpe andre private tilbud og/eller gi et omfattende tilbud ved nærskolen. Avtalen med Horten kommune har 2 årsoppsigelsestid.</p>
```

```{=html}
<p>Forebyggende helse: Rideterapi       Fysioterapeut 10-20% stilling       170       En fysioterapeut eier 100% stilling og har dette som en del av sin stilling.</p>
```

```{=html}
<p>Helsestasjoner utover en       Helsestasjon 0-5 år er et gratis og lovpålagt helsetilbud for barn og foreldre fra fødsel til skolestart. Kommuenn har i dag 3 lokasjoner derav 1 er lovpålagt.       950       En eventuell reduksjon i antall helsestasjoner må utredes nærmere. En reduksjon vil kunne redusere behov for administrative ressurser, men vil også medføreulemper for brukerne av helsestasjonene.</p>
```

```{=html}
<p>Psykisk helse/Familiehuset: Homestart       Frelsesarmeen drifter Homestart . En frivilligbank med hjelpere som hjelper inn i familier en periode.       530       Pengene er plassert i Familiehusets budsjett. En kan si opp samarbeidet med 6 måneder frist.</p>
```

```{=html}
<p>Psykisk helse/familiehuset Ung Arena +       Tjenestene skal samarbeide og drive sammen, men det er ikke beskrevet hvordan.       91       Familiehuset har ansatte på Ung Arena + mandag, tirsdag og onsdag. Tirsdag og onsdag er det Helsestasjon for ungdom og da er det godt besøkt. Mandag er det fåbesøkende fra aldersgruppen 13-18 år.</p>
```

```{=html}
<p>Åpen barnehage       Tilbud til familier uten barnehageplass       765       Åpen barnehage i sentrum kan avvikles ettersom Tønsberg kommune er eier.1. Nedleggelse. Innsparing 80% stilling2. Redusere til en dag per uke. Innsparing 40 % stilling.Tilbudet er fullt ut benyttet begge åpningsdager. Vi mister kontakten med familier vi kan veilede inn i ordinær barnehageplass, samt en viktig arena forsmåbarnsfamilier å møte andre/bygge nettverk/få venner.Kommunen gir tilskudd til åpen barnehage på Bjerkely. Denne er godkejnt som åpen barnehage etter barnehageloven, og har dermed rett til tilskudd.</p>
```

```{=html}
<p>Økt grunnbemanning i barnehage       Kommunen har gjennom politiske vedtak økt grunnbemanningen imed 21 årsverk i de kommunale barnehagene. To årsverk er videre bevilget i 2025 og 2026, men de er foreløpig ikke iverksatt fordi barnehagne også måtte effektuere et tildligere Handlingsrom 2024 tiltak på 1,6 mill.       22 400       Årskostnaden i de kommunale barnehagene er ca. 14 mill. (+ 1,5 mill. midlertidig i 2025 og 2026).Tilskuddet til de private barnehagene øker med ca. 60% avkostnadene i de kommunale barnehagene.</p>
```

```{=html}
<p>Logopedtjenesten       4,1 stilling ansatt som lærere. Har individuelt tilrettelagt opplæring med elever som har behov for logoped (som ikke har rett til logoped gjennom helselovgivning) og spesialpedagogisk hjelp i barnehagen.       2 700       Individuelt tilrettelagt opplæring med logoped er lovpålagt, men ikke hvordan dette er organisert i Tønsberg kommune. Heller ikke omfanget er lovpålagt.Vi ser atandre kommuner har logopeder ansatt i PPT, som veileder ut i barnehage og skole, men som ikke gjennomfører undervisning. Det vil da være behov for å kjøpeprivate tjenester, slik de andre kommunene gjør, men usikker på om dette dekkes av HELFO eller kommune? Dette må eventuelt utredes.</p>
```

```{=html}
<p>Forsterket fraværsteam       1 stilling delt på to ansatte i PPT. Jobber i grenseområdene til flere støttetjenester. Koordinerer skole, hjem, andre tjenester i saker med fastlåst og stort skolefravær. Veileder foreldre og kan ha samtaler med eleven       800       Oppgavene er for så vidt lovpålagte, men i ulike lovverk. Nedleggelse av teamet vil føre til oppsigelse av en stilling innenfor PPT</p>
```

```{=html}
<p>MST-CAN       MST-CAN jobber i de alvorligste barnevernssakene for å forhindre at barn må flytte fra hjemmet. MST-CAN (Multisystemic Therapy – Child Abuse and Neglect) er et evidensbasert behandlingstiltak for familier med barn mellom 6 og 18 år, hvor det rapporteres om fysisk vold og / eller omsorgssvikt i hjemmet. Metoden er en tilpasning av Multisystemisk terapi (MST), som i Norge er en veletablert behandling for familier med ungdom som har alvorlige atferdsvansker.       3 900       MST_CAN er et tungt barnevernstiltak og er viktig for at barneverntjenesten kan si at vi tilbyr et forsvarlig tiltak i de alvorlige sakene. MST-CAN er regulert av eninterkommunal samarbeidsavtale mellom Larvik, Horten og Tønsberg. Avtalen er politisk behandlet. Avtalen er bundet for 5 år frem til 31.12.27. Fra den datoen kanTønsberg si opp avtalen med 12 måneders varsel/oppsigelsestid. Tønsberg kan tidligst tre ut av avtalen 1 januar 2029.</p>
```

```{=html}
<p>Ambulerende skolemiljøteam (ASMT)       Ambulerende skolemiljøteam er et tilbud til de kommunale skolene. Teamet skal jobbe både direkte inn i miljøet på skolen der utfordrende situasjoner oppstår og har vedvart over tid, og med forebyggende hensikt for å unngå at utfordringer skal oppstå. Tiltakets hovedmålsetting er å involvere barn og unge i å skape løsninger på utfordringer selv, og dermed sikre medvirkning i saker som betyr mye for dem. Videre er målet at det settes inn riktig tiltak både på individuelt- og systemnivå.       6 000       Er allerede delvis vurdert. Teamet er redusert fra 6 til 4 ansatte og rammen til barnevern er justert ned med 2 millioner.</p>
```

```{=html}
<p>Forebyggende barnevern       Forebyggende barnevern skal bidra til å styrke kommunenes forebyggende arbeid og tidlig innsats i hele oppvekstsektoren gjennom tilstedeværelse i skole/barnehage og andre tverrfaglige arenaer/grupper.  Samordning og samarbeid er essensielt for å gi barn og familier rett hjelp til rett tid.  Alle tjenestene har et selvstendig ansvar for å gi den hjelpen de er pliktige til etter regelverket.  Barneverntjenesten skal ved sin forebyggende funksjon bidra til dette. Veiledning/ støtte til barn,unge, foreldre og ansatte.       5 000       I henhold til ny lov skal barneverntjenesten jobbe for å forbygge omsorgssvikt og atferdsproblemer. Barneverntjenesten har løst det ved å ha egne ressurser somjobber forebyggende. De ansatte i forebyggende barnevern er ikke nye stillinger eller midler som ble tilført barneverntjenesten, men stillinger som ble omprioritertintert fra barneverntjenestens eksisterende ramme. De skal imøtekomme det lovpålagte kravet om forebygging i barnevernet. Dersom forebyggende barnevern skalendres/fjernes i den formen den er, må virksomheten finne andre ressuser og metoder for å imøtekomme den lovpålagte oppgaven. Alternativ 1: Reduserebemanningen i teamet Alternativ 2: Legge ned tilbudet . Dersom tilbudet legges ned, må barneverntjenesten finne andre ressurser fra lovpålagte oppgaver til å bidramed forebyggende arbeid. Forebyggende barnevern deltar i alle tverrfaglige- og ressursteam i skole og barnehage. Det må andre ansatte dekke opp.</p>
```

```{=html}
<p>Søskenmoderasjon SFO og barnehage       Moderasjonsordningene i barnehage følger kravet i forskrift til barnehageloven § 3. Moderasjonsordningen knyttet til lavinntekt i SFO følger kravet i forskrift til opplæringslova § 2-4. Søskenrabatt i SFO er regulert i kommunal forskrift om skolefritidsordningen § 6 og vedtas/endres av kommunestyret uten at det er krav til denne type moderasjonsordning i sentral lov eller forskrift. Det gis 30 % rabatt for 2. barn og 50 % rabatt fra 3. barn.       460       Søskenmoderasjon i skolefritidsordningen (SFO) er ikke lov- eller forskriftsfestet. Moderasjonsordningen med satser vedtas/endres av kommunestyret i forbindelsemed budsjettbehandlingen. Innsparingseffekt er basert på prognosen for 2025.</p>
```

```{=html}
<p>Mestring og helse</p>
```

```{=html}
<p>Frisklivssentral       Helsetilbud med fokus på forebyggende helsearbeid. Gruppetilbud ulike treningsformer. Mange lavterskel mestringskurs/ endre adferd tilbud. Henvisning fra fastlege, fysioterapaut, sykepleier eller annet helsepersonell. Alle kommuner skal ha et tilbud om forebyggende helsetjenester til befolkningen. Frisklivssentral er en anbefalt måte å organisere slike tjenester på, og er en del av kommunens samlede helsetilbud. Har ansatt fysioterapeut(er) ergoterapeut og psykolog. Samarbeid med lærings og mestringskoordinator. Mange ulike mestringskurs som går fast hvert semester + prosjektdrevne kurs med midler fra fylkeskommunen eller helsedirektoratet. Er utviklingssentral for Vestfold. To lokasjoner - en på Rema 100 hallen på Tolvsrød og en på Re helsehus -mange av gruppene i den delen av kommunen gjennomføres på Våle samfunnshus       3 892       Reduksjon i tilbudet kan gi lavere mestring, trivsel og levekår for utsatte grupper av befolkningen. Lavere grad av forebyggende helsetjeneste vil kunne gi støøre behovfor helsehjelp tidligere i livet, med økt totalkostand for kommunen</p>
```

```{=html}
<p>Aktivitetshus       Kommunen har fire aktivitetshus. Aktivitetshusene er sosiale møteplasser med varierte aktiviteter og kulturarrangementer. Åpent tilbud for alle innbyggere over 18 år.Kom gjerne innom, så kan du få mer informasjon og en omvisning. Stor grad av frivillig innsats inn i drift av tilbudene.       15 811       Konsekvenser av å legge ned disse, er bl.a. økt ensomhet, økt sykelighet og utenforskap. Ytterste konsekvens, kan være økte utgifter i hjemmetjenesten.</p>
```

```{=html}
<p>Transportjenesten       Kommunen har egen transporttjeneste. Arbeidstakere, som ikke kan benytte ordinære transportmidler, kan søke om tilrettelagt transporttjeneste. Her betaler den enkelte egenandel       5 929       Tar ned det nederste trinnet i omsorgstrappa som kan forebygge ensomhet, utenforskap og større hjelpebehov på et høyere nivå i Tønsbergtrappen, når personer ikkekommer seg til aktiviteter og sosiale møteplasser . Brukere med vedtak på dagsenter demens, rehabilitering, arbeid + aktivitetshus vil ikke kunne nytte dissetjenestene. Brukerne kommer seg ikke dit v- de er avhengige av transpottjenesten</p>
```

```{=html}
<p>Kommunale hjelpemiddel tjeneste       Interkommunalt (vertskommunesamarbeid) lager for korttidshjelpemidler, utkjøring og veiledning til innbyggere (80 - 85 000 innbyggere) i Tønsberg og Færder. Det største lageret i Vestfold /Telemark. Mottak av hjelpemidler fra hjelpemiddelsentralen (NAV) og utkjøring av disse. Mye kommer flatpakket, må skrus sammen, repareres - store hjelpemidler m/elektronikk.       4 802       Reduksjon i tilbudet fører til at hjemmeboende med pleiebehov ikke kan bo hjemme. Innbyggere med lavere grad av hjelpebehov klarer seg lengre hjemme medriktige hjelpemidler. Utsetter mer ressurskrevende tjenester 1-10</p>
```

```{=html}
<p>Rehabiliteringstilbud i institusjon       Rehabilitering korttidspasienter og hjemmeboende med rehabiliteringsbehov, tilrettelegging I hjemmet før hjemreise fra institusjon       4 230       Tjenesten samorganiseres med annen virksomhet, økt behov hverdagsrehabilitering i hjemmet, dagsenterplasser, ventetid ergo/fysio, fare for økt liggetid institusjon</p>
```

```{=html}
<p>Frivilligkoordinator, LMS, kreft- og demenskoordinatorer       Frivilligkoordinator 1 ansatt - 100% stilling. Bygger nettverk av frivillig kontakter som ivaretar de frivillige og deres bidrag/innsats ute i tjenestene. Samarbeider med frivilligsentralene. Kreftkoordinatorer 2 ansatte - 150% stilling. Gir tjenester til hjemmeboende kreftsyke til behov opphøre ved innleggelse institusjon/eller død. Støtte og veiledning til kreftoverlevere og pårørende. Samarbeid og veiledning med/av hjemmetjeneste, kortidsopphold i institusjon, spesialist helsetjeneste. Kreftkoordinatorer 2 ansatte - 150 % stilling. Gir tjeneste og veiledning til hjemmeboende personer med demens og deres pårørende , fortrinnsvis hjemmebesøk. Samarbeid med THO, spesialisthelsetjeneste, NAV, dagsenter,ergoterapueter. Veiledning av annet personell , opplæring av frivillige til tilbud som "aktivitetsvenn til personer med demens" til gåfotball, demenskafe, demensvennlig samfunn - opplæring i demens for næringsliv , taxi,buss. Samarbeid med frivillig og LMS koordinator, frivilligsentralen og den lokale demensforeningen. Er med å arrangere pårørende kurs til pårørende til personer med demens. Samarbeid med Færder. Tønsberg har ansvar på vinter /tidlig vår og Færder om høsten .       2 855       Se spesielt helse- og omsorgstjenesteloven § 3-6 - kommunens ansvar for pårørende. Disse tilbudene utsetter behov for mer ressurskrevende tjenester. Er godestøtte og avlastningstiltak for pårørende</p>
```

```{=html}
<p>Aktiv på dagtid       Tilbud for de som er ufrivillig utenfor arbeidslivet og er mellom 18 og 67 år -administres fra Sidebygningen, vertskommuneavtale med Færder.       550       Økt ensomhet og reduksjon i aktivisering og sosialisering av personer som står utenfor arbeidslivet. Kan bidra til raskere fallering av fysisk og psykisk helse, som igjenkan føre til behov lengere opp i Tønsbergtrappen</p>
```

```{=html}
<p>Tilrettelagt arbeid og aktivitet, kjøpte arbeidsplasser (varig tilrettelagte arbeidsplasser, VTA), og varig tilrettelagt i ordinær bedrigt (VTO) Denne enheten har også ansvar for VI på Hogsnes og VI på Torvet - samarbeider med NAV ung       Tilrettelagte arbeidstilbud for mennesker med nedsatt funksjonsevne eller som av andre ulike årsaker står utenfor det ordinære arbeidslivet. https://www.tonsberg.kommune.no/tjenester/helse-og-omsorg/aktivitet-og-mestring/tilrettelagt-arbeid/       22 599       Vedtaksbasert. Tilbud i egen kommune i Årfugleveien 4, på Kilen gjennom utegtruppa og ved Re dagaktivitetssenter v/ tidligere Våle sykehjem. Kjøpte VTA plasser vedSmiløkka, Tangent, Revetal arbeid og kvalifisering (RAK)og Via Færder for 90 innbyggere. ca 20 innbyggere i VTO plasser. Innbyggerene i VTA og VTO har et høyerefunksjonsnivå enn tilbudene i egen kommune. VI tiltakene har en målsetting om å motvirke ungt utenforskap. Samarbeid med Nav ung om målrettet arbeidstrening,mestring. Tilbud til samme målgruppe i MFT's lokaler i Kilengat 37.</p>
```

```{=html}
<p>Kulturkontakt Re helsehus       40% stilling. Tilrettelegger for kulturelle aktiviteter på Re helsehus       500       Ved bortfall kan det gi lavere trivsel og færre møteplasser for beboere og pårørende.</p>
```

```{=html}
<p>Kultur/frivilligkontakter       Samlet 1,8 årsverk som benyttes I hjemmesykepleie og sykehjem/helsehus       1 250       Disse kontaktene bidrar til å opprettholde kontakten med frivillige ressurspersoner i kommunen som ikke mottar lønn. Konsekvensen kan bl.a. være tap avhelsefremmende hverdagsliv og gir mindre grad av gode møteplasser. Tap av meningsfull og inkluderende hverdag for eldre.</p>
```

```{=html}
<p>Kurs for innbyggere       Kurstilbud til voksne over 18 år. Pårørendekurs, frivilligkurs, mestringskurs mv. De fleste kursene er gratis. MFT, PHA eier i hovedsak disse tjenestene. Mye er tilskuddsbasert. LMS koordinator, psykolog, frisklivssentralen, frivillighetskoordinator bidrar. Jobber i hele sektor MH og i andre sektorer. Søker prosjektmidler, gjennomfører prosjekter. Iverksetter mestring/endringskurs for alle innbyggere. Samarbeider med frisklivsentralen , frivillighet,psykisk helse og andre relevante virksomheter/sektorer. Endrings og mestringskurs - også for pårørende. Er kommunens ressurs person i opplæring av instruktører Hjerte/lungeredning.       1 000       Kursene kan forebygge ensomhet, utenforskap, psykisk og fysisk uhelse. En reduksjon eller bortfall kan føre til større hjelpebehov på et høyere nivå iTønsbergtrappen. Det kan gi negative konsekvenser for andre sektorer enn helse- og omsorg, f.eks arbeidsliv, generell mestringskompetanse. Lovpålagt etter § 3-6:Første ledd nr. 1: Til personer med særlig tyngende omsorgsarbeid skal kommunen tilby nødvendig pårørendestøtte blant annet i form av opplæring og veiledning.Vurdere nivået og organisering.Lavterskel tilbud/kurs forsvinner. Må vurderes. Lovpålagt etter § 3-6: Første ledd nr. 1: Til personer med særlig tyngendeomsorgsarbeid skal kommunen tilby nødvendig pårørendestøtte blant annet i form av opplæring og veiledning.</p>
```

```{=html}
<p>Taxitransport i skoleferier som avlastende tiltak       Transport til og fra avlastningstiltak, inkludert i skoleferier, er lovpålagt i Norge. Ifølge helse- og omsorgstjenesteloven § 3-6, skal avlastningstiltak inkludere transport, ledsager, mat og lignende       263       Mange innbyggere, spesielt eldre, personer med funksjonsnedsettelser, og de uten tilgang til bil, vil få vanskeligheter med å komme seg sosiale elleraktivitetsarenaer. Bortfall kan føre til økt ensomhet, lavere aktivitetsnivå og redusert livskvalitet</p>
```

```{=html}
<p>Sidebygningen       Sidebygningen er et tilbud til mennesker med psykiske plager og, eller utfordringer knyttet til rus.Vi tilbyr sosiale møteplasser og aktiviteter som trening, syverksted, kreativt verksted, quiz, bingo, karaoke og mye mer. Aktiv på dagtid og tilrettelagte fritidsaktiviteter administeres fra Sidebygning. Det samme gjør Brobyggertiltakene i KIlengata 37. Tilsvarende tilbud i tidligere Re kommune, TREffpunktet og grønn omsorg adm fra Sidebygningen - dette er ikke interkommunalt med Færder. Grønn omsorg gir vedtaksbaserte tjenester. Sidebygningen gir også kveldstilbud/aktiviteter til personer med nedsatt funksjonsevne. De gjennom føres utenfor Sidebygningen.       9 717       Tjenesten er rettighetsbastert, men ikke nivået. Tar ned det nederste trinnet i omsorgstrappa som kan føre til økt hjelpebehov, ensomhet, økt utenforskap og størrehjelpebehov på et høyere opp i Tønsbergtrappen. Det kan også føre til lengre forløp i vedtaksbaserte tjenester, da det ikke vil være et tilbud å skrive ut til. Kanvurdere nivå og organisering</p>
```

```{=html}
<p>Tilrettelagt fritidsaktiviteter for personer over 16 år m/funkjsonsnedsettelser. Budsjett samlet under sidebygningen       Fritidsaktiviteter tilrettelagt for personer over 16 år med funksjonsnedsettelser. Blant annet fritidsklubb, håndball, fotball, musikk og bevegelse. - administret fra Sidebygningen -vertskommunesamarbeid med Færder.https://www.tonsberg.kommune.no/tjenester/helse-og-omsorg/aktivitet-og-mestring/tilrettelagt-fritid/       550       Økt ensomhet og reduksjon i aktivisering og sosialisering av personer som har funksjonsnedsettelser. Kan bidra til raskere fallering av fysisk og psykisk helse,utenforskap, økt ensomhet. Dette kan igjen føre til behov lengere opp i omsorgstrappen</p>
```

```{=html}
<p>Tønsberg Demenskor       Kor for personer med demens, målgruppen er hjemmeboende. Ikke vedtaksstyrt. Demenskoordinatorene er de som anbefaler og rekrutterer sangere       200       For noen er dette per idag et tilbud som er det eneste de har av tilbud i kommunen. Å legge ned tilbudet vil kunne gi økt ensomhet og fremskynde andre behov fortjenester fra kommunen</p>
```

```{=html}
<p>Feltpleie       Feltpleie er et gratis, ubyråkratisk og fleksibel lavterskel og gatenært poliklinisk helsetilbud for rusmiddelavhengige. Brukere kan møte opp uten timeavtale, være anonym, enten edru eller påvirket, og kan få helsehjelp, samtale, råd og veiledning, og blant annet få rene sprøyter for å forebygge smitte. Formålet med tilbudet er å redusere overdoser og overdosedødsfall, forbedre livskvalitet og helsetilstand hos brukere, og å kanalisere rusmiddelavhengige til etablerte hjelpeinstanser.       3 200       Tjenesten er delvis rettighetsbastert, men ikke nivået. Brukerne har rett på nødvendig helsehjelp på lik linje med andre innbyggere. Tar ned det nederste trinnet iomsorgstrappa som kan føre til økt hjelpebehov og større hjelpebehov på et høyere opp i Tønsbergtrappen. Kan vurdere nivå og organisering</p>
```

```{=html}
<p>Kultur og samfunnsutvikling</p>
```

```{=html}
<p>Kultur, idrett og folkehelse</p>
```

```{=html}
<p>Fritidskort       Midler som år til barn og unge og deres fritidsaktiviteter       300       Får ikke anledning til å betale kontigenter for barn og unge fra lavinntektsfamilier. Pr i dag er det 1800 barn som er registrert som mottagere av kontigenter eller andretjenester. Videre søkes det midler fra Bufdir.</p>
```

```{=html}
<p>Friskus       Digital plattform       200       Lisens for den digitale plattformen, Friskus, som gjør det mulig å tildele midler samt se aktiviteter og tilbud for innbyggerne</p>
```

```{=html}
<p>Historisk satsning alternativ 1       Vedtatt sastningen på vikingtid og middelalder       600       Slutter å satse på vikingtid og middelalder, dette får konsekvenser for frivillige lag og foreninger, historisk fagmiljø i Tønsberg og andre virksomheter som jobber meddette temaet. Foreslås halvert i Sunn kommuneøkonomi</p>
```

```{=html}
<p>17. mai arrangement       17. mai feiring       370       Midlene går til vakthold ifbm 17. maitogene, salutt, kranser som legges ned ved minnebautaer og andre minnesmerker. Summen dekker feringene på Revetal og iTønsberg sentrum. I tillegg er det kostnader for teknisk drift og brannvesen som går fra budsjettet til Teknisk drift.</p>
```

```{=html}
<p>Annonsering av 17. mai arrangement i Tønsbergs Blad       Annonsering i avis       40       Det antas at mange innbyggere får informasjonen om 17. mai - feiringen i andre kanaler enn avisa. Det kan allikevel skape problemer for de personene som først ogfremst finner sin informasjon i avisa.</p>
```

```{=html}
<p>Tilskudd til skolene ifbm 17. mai       Det er FAU'ene på skolene som lager 17. mai - feiringen på skolene. Alle FAU'er får kr. 2000 som en start til arrangementet       50       Konsekvensen kan være at det kan bli utfordrene å få kjøpt inn varer til feiringen på forhånd før de begynner å tjene penger på selve dagen</p>
```

```{=html}
<p>Prisutdelinger       Kulturprisen deles ut en gang i året etter politisk vedtak       50       Konsekvensen vil være at Tønsberg kommune ikke har anledning til å gi ut et synlig bevis på heder til frivillige personer eller lag/foreninger.</p>
```

```{=html}
<p>Støperiet       Drift og lønn       250       Betyr stenging</p>
```

```{=html}
<p>Haugarock       Drift       160       Betyr stengning, dette tilbudet treffer ungdom som ikke benytter andre fritidstilbud i kommunen. Det er få andre øvingsmuligheter i kommunen.</p>
```

```{=html}
<p>Vestfoldmuseene       Eierandel       5 230       Usikker på om denne da vi er eier</p>
```

```{=html}
<p>Kulturminneforvaltning       Skjøtsel, ruinpleie av middelalderruinene       200       Skjøtsel av Middelaldersruiner bortfaller</p>
```

```{=html}
<p>Kunstformidling       Egenandel til DKS (Den kulturelle skolesekken)       140       Tilbudet til barn og unge i alle skoler i Tønsberg blir redusert</p>
```

```{=html}
<p>Offentlige markeringer       22. juli og 8. mai       50       Tilbudet om minnemarkeringer blir borte</p>
```

```{=html}
<p>Medlemskap       NOKU       22       Mister informasjon og nettverk som kommer gjennom medlemskapet</p>
```

```{=html}
<p>Tønsberg svømmehall for publikum       Kun skolesvømming og til lag og foreninger       100       Mister et meget viktig folkehelsetilbud som ikke koster mye for publikum å bruke. Som en kystkommune er svømmekompetanse ekstra viktig. Tap av billettinntekter.</p>
```

```{=html}
<p>Omstrukturere åpningstider i Tønsberg svømmehall       Morgenbad, herre/damebad       50       Mister et viktig forebyggende folkehelsetiltak, i tillegg mister de kvinnene som kun kan bade med andre kvinner tilbudet sitt.</p>
```

```{=html}
<p>Publikumsbad Revetal       Tirsdag og torsdag ettermiddag (oktober - mai) virksomheten har kun publikumsbad på Revetal. Skolene har selv ansvret for skolesvømmingen       250       Mister et viktig forebyggende folkehelsetiltak for innbyggerne på Revetal</p>
```

```{=html}
<p>Tilskudd foreninger barn og unge kultur       Tilskudd foreninger barn og unge kultur       650       Redusert tilbud</p>
```

```{=html}
<p>Tilskudd voksenkorps       Tilskudd voksenkorps       200       Redusert tilbud</p>
```

```{=html}
<p>Tilskudd historiske lag og foreninger voksne       Tilskudd historiske lag og foreninger voksne       200       Redusert tilbud</p>
```

```{=html}
<p>Tilskudd festivaler og store arrangement kultur       Tilskudd festivaler og store arrangement kultur       950       Redusert tilbud</p>
```

```{=html}
<p>Tilskudd til foreningseide anlegg kultur       Tilskudd til foreningseide anlegg kultur       275       Redusert tilbud</p>
```

```{=html}
<p>Tilskudd foreninger voksne kultur       Tilskudd foreninger voksne kultur       450       Redusert tilbud</p>
```

```{=html}
<p>Utesvømming       Skolesvømming ute (9 skoler)       50       Vil resultere i at barn og unge ikke får en realistisk øving ifht kompetansekrav i Læringsplanen</p>
```

```{=html}
<p>Tilskudd lag og foreninger idrett iog friluftsliv anlegg       Driftsstøtte til idrettsanlegg       2 460       Tilskudd som inkluderer strømkompensasjon, anleggsstøtte og drift av foreningseide anlegg. Konsekvensen av å skjære ned på dette tilskuddet vil gi foreningenestrammere økonomi og i ytterste konsekvens kan dette føre til innløsning av kommunale lånegarantier (for de foreningene som har dette)</p>
```

```{=html}
<p>Tilskudd lag og foreninger idrett og friluftsliv medlemsstøtte       Støtte pr medlem i lag og foreninger       1 450       over deres evne til å opprettholde sine forpliktelser på lån etc som igjen vil kunne medføre at kommunal lånegaranti må innløses dersom de har det.</p>
```

```{=html}
<p>Tilskudd lag og foreninger idrett og friluftsliv ski- og løypenett       Tilskudd til dugnadsgrupper som merker og rydder stier og løyper i kommunen       210       Konsekvensen kan være at stier og løyper ikke blir ryddet og merket</p>
```

```{=html}
<p>Tilskudd lag og foreninger idrett og friluftsliv Særskilt støtte       Tilskudd til Tønsberg idrettsråd og Tønsbergs funksjonshemmede idrettsforening       110       Redusert støtte vil kunne gi et redusert tilbud</p>
```

```{=html}
<p>Tilskudd lag og foreninger idrett og friluftsliv Skolenære anlegg       Støtte til idrettslag med skolenære anlegg       110       Redusert støtte vil kunne gi et redusert tilbud</p>
```

```{=html}
<p>Skjærgårdstjenesten       Tønsberg er eier av Skjærgårdstjenesten sammen med Sandefjord og Færder       430       Forankret i avtale om drift av skjærgården. Vedlikehold av brygger, forsøpling m.m. ute i skjærgården. Avtale sammen med Færder kommune. 1 års oppsigelse. Måsies opp ved utgangen av året.Tønsberg betaler litt 43% og Færder resten.</p>
```

```{=html}
<p>Oslofjorden friluftsråd       Medlem       230       Samarbeid om kystledhytte, skilting, samarbeid om friluftslivsforvaltning, forvaltningsplaner m.m. 1 års oppsigelse.</p>
```

```{=html}
<p>Ung i Tønsberg</p>
```

```{=html}
<p>Åpne møteplasser for ungdom       Gratis, åpne møteplasser for ungdom i alderen 13-18 år. Fem åpne møteplasser, på Vear, Slagen, Sem, Eik og Revetal. Mat og inkluderende fellesskap, latter og moro. Eksempel kostnad Slagen: 350 i lønn, 60 i mat       3 500       Stort sett lønnskostnader, ti stillinger i ulik størrelse. Søker prosjektmidler for drift og utstyr utover mat. Ved kutt mister ungdom et sted å være i sitt nærmiljø. Spesieltuheldig for de som ikke har tilhørighet i andre fritidsaktiviteter. Forebygger utenforskap. Kutt her gir større utgifter lenger opp i trappa. Ansatte som jobber på klubbjobber også inn på Ung Arena+, dermed reduseres bemanningen i velkomstområdet på Ung Arena+</p>
```

```{=html}
<p>Utekontakten       Oppsøkende sosialfaglig arbeid spesielt rettet mot sårbare grupper.       2 600       Lønn til tre stillinger oppsøkende gjør at kommunen treffer utsatte unge, og har oversikt over utsatte miljø som øvrige deler av kommune og ulike hjelpetjenester fårdel i. Oppsøkere har også oversikt over miljø med unge fra nabokommuner, som utgør en stor del av risikoutsatte unge i sentrum, og kontakter nabokommuner. Ungesom er i sentrum har trygge voksne til stede. Innbyggere rapporterer trygghet ved deres synlige tilstedeværelse. Konsekvens er at det blir redusert eller fraværende.Kutt her vil sannsynlig gi økte utgifter lenger opp i trappa. En ansatt har fast vakt på Ung Arena+, dermed reduseres bemanningen i velkomstområdet på Ung Arena+.</p>
```

```{=html}
<p>UngdomsLos       Lavterskel oppfølging av unge med skolefraværsproblematikk       1 735       Lønn til tre stillinger, tilsammen 210%, gjør at kommunen møter unge med skolefravær med en lavterskel tilnærming. Både individuelt arbeid, og gruppetilbud isamarbeid med PPT. Konsekvens er at tilbud til unge som er i ferd med å falle utenfor utdanningsløpet blir redusert. Kutt her kan gi utgifter lenger opp i trappa. Enansatt jobber fast 4 timer på Ung Arena+, ved kutt reduseres bemanningen på UA+</p>
```

```{=html}
<p>Juniorklubber       Åpen møteplass for 6 - 7 trinn       410       350' i lønnsmidler og 60' i mat. Samarbeid med ungdomsskolen og faget innsats for andre. Ungdomskoleelever er gode rollemodeller for de yngre. Et vinn vinnsamarbeid. Ved kutt blir det færre tilbud spesielt for de som ikke benytter seg av organisert aktivitet.</p>
```

```{=html}
<p>Ungdomskoordinator       Ungdomskoordinatoren koordinerer tjenester og prosjekter som berører ungdom       890       Ingen lovpålagt oppgave, men støtter opp om det lovpålagte tjenestetilbudet. Oppgaver må ivaretas av andre funksjoner i kommunen</p>
```

```{=html}
<p>Ungdomsdrevet Kafe (Kafe No8)       Åpen møteplass. Gratis kafe for ungdom drevet av ungdom       750       Kafeen kom i stand på initiativ fra de unge selv. De har malt vegger og kjøpt møbler. Tre unge ansatte, en 50% og to i 33% stillinger. Dette er unge mennesker som harstått utenfor arbeid og utdanning, og gjennom trygg veiledning og ansvar, har vokst inn i oppgaven og drifter nå kafeen som er åpen hver dag fra 1500-1800. Ved kuttmister vi en arena for mestring og mening for unge utenfor arbeid og utdanning. Ungdom fra 15 år og oppover mister et sted å være, et inkluderende sted for samværmed andre i sentrum. Forbygger utenforskap og kan være et første steg for de som synes det er litt skummelt å gå inn døre på Ung Arena+.</p>
```

```{=html}
<p>Aktiviteter i skolens ferier       Turer og arrangementer i skolens ferier       20       Prosjektmidler fra Bufdir finansierer turer og aktiviteter i skolens ferier. Dette er tilbud spesielt rettet mot unge i lavinntektsfamilier. Lønnskostnader til ansatte på ca.20'. primærbemanning fra de som jobber på ungdomsklubb. Gjennomføringen fordrer at andre tiltak består, slik at vi har ansatte til å gjennomføre. Ved kutt er det liteå spare.</p>
```

```{=html}
<p>FLYT       Samarbeid mellom kronprinsparets Fond og Tønsberg kommune. Hovedformål : gi ungdommene verktøy til å håndtere livet, sette seg mål og fullføre videregående skole.       150       150' i prosjektmidler fra Kronprinsparets fond og 150' i lønnsmidler fra kommunen. Dette er et svært vellykket samarbeid med kursledere fra Forebyggendebarnevern og Ung i Tønsberg. Ungdommene rekrutteres i 9. klasse og følger programmet gjennom hele skoleåret i 10. klasse og i overgangen til videregående utseptember. Gruppa møtes på fritiden og finner fellesskap og motivasjon til å fullføre studier og arbeid. Indirekte konsekvenser for utenforskap og frafall fra skole,samt mulig økte utgifter lenger oppe i trappa..</p>
```

```{=html}
<p>UKM       UKM (Ung kultur møtes) er en arena der ungdom møter ungdom, der kultur utveksles, uten konkurranse, men med tanker om utvikling, læring og samhold.       100       Personalressurser. Kostnad holdes lav da vi gjør dette i samarbeid med Færder. En inkluderende arena for ulike kulturelle uttrykk bortfaller ved kutt.</p>
```

```{=html}
<p>Fredagsgruppa       Selektert gruppe med spesielt sårbar ungdom. Fokus på livsmestring, fysisk trening for å kunne håndtere følelser og oppnå selvkontroll.       180       Lønnsmidler og ca 30' til mat. Ved kutt bortfaller en viktig arena for en ekstra sårbar gruppe. Et særdeles vellykket og viktig tiltak for å forebygge kriminalitet ogutenforskap. Gruppens medlemmer er ofte kjent i kommunens øvrige hjelpetjenester.</p>
```

```{=html}
<p>SLT - koordinator       Koordinering av det kriminalitetsforebyggende arbeidet. Samarbeider tett med politiet og på tvers av fagfelt i kommunen.       515       50% stilling i kombinasjon med tjenesteleder for Ung Los. Et kutt her vil få konsekvenser for kommunens tverrfaglige og forebyggende arbeid rettet mot unge, samtforebygging av kriminalitet.</p>
```

```{=html}
<p>Radikaliseringskontakt       Koordinerer arbeidet mot radikalisering og voldelig ekstremisme.       300       Leder en tverrfaglig sammensatt gruppe, samt en mentorordning med 4 mentorer. Samarbeider tett med politiet og i flere tilfeller det siste året PST. 30% stilling ikombinasjon med tjenesteleder for ung inkludering. Et kutt her vil forringe kommunens mulighet til å avverge eller handle raskt og riktig ved alvorlige truendehendeler.</p>
```

```{=html}
<p>Innholdsproduksjon sosiale medier       Ung person i 50% stilling for å nå ungdom der de er på sosiale medier. Ansvar for kommunikasjon ut for alle våre tilbud, og veiledning av de to lærlingene i innholdsproduksjon.       450       Et kutt her vil gå utover informasjon ut til ungdommen, og evne til å møte de der de er på sosiale medier. Ved kutt går det ut over veiledning til de to lærlingene iinnholdsproduksjon med lærlingsløp til juli 2026. Det nytter ikke å ha gode tjenester om ingen vet om det.</p>
```

```{=html}
<p>To lærlinger i innholdsproduksjon       Lærlingene jobber med kommunikasjon ut til ungdommene på sosiale medier, med hovedvekt på Ung Arena+ og Ung i Tønsberg sine tiltak. Et samarbeid med Kommunikasjonsavdelingen.       280       280 er kost for UiT etter refusjon for lærlinger. Ved kutt her bortfaller en viktig læringsarena for unge i innholdsproduksjon. De unges blikk sikres i utvikling oginformasjon ut av våre tilbud. Samarbeid med kommunikasjonsavdelingen styrker helhetsblikket og øker kunnskapsnivået for lærlingene.</p>
```

```{=html}
<p>Bibliotek       Det er lovpålagt å ha et bibliotektilbud, men omfang er ikke lovpålagt. Tønsberg kommune har bibliotek i Tønsberg og på Revetal.       25 400       Summen viser hele komunens kostnad knyttet til bibliotekvirksomhet inkludert bygningsmessige kostnader.</p>
```

```{=html}
<p>Skolebibliotekkoordinator       Ikke lovpålagt. 50% stilling       407       Denne stillingen eies kun at Tønsberg kommuner (deles ikke med færder) og er knyttet til spesifikke arbeidsoppgaver: Samling for skolebibliotekarer, organisering avtjenester rettet mot skolene osv.</p>
```

```{=html}
<p>Friby Tønsberg       Gir beskyttelse til en forfulgt forfatter, vedkommende får en av "palssene" i kvota som TBG skal ta, vedkommende får spesiell oppfølging av biblioteket       70       Vi har i dag god kontakt med flykningkoordinatoren og de kan jo bare gi beskjed hvis det kommer en forfatter i den "vanlige" kvota. Da trenger vi heller ikke betaleavgift til Stavanger kommune for å være med i ICORN)</p>
```

```{=html}
<p>SMART-senter       SMART senteret er en ikke lovpålagt kommunal virksomhet som jobber både internt i egen kommune og utadrettet til resten av landet. et kompetansesenter som har utviklet seg gjennom 20 år og har en sterk standing mot internt, nasjonalt og politisk.       2 700       Senteret har utviklet metoder og kunnskap som har hatt stor innvirkning på oppvekst, ledelse og arbeidsmiljø i både Tønsberg og mange andre kommuner rundt om ilandet. Storåarten av SMART sitt budsjett kommer fra inntekter fra salg av kurs utenfor kommunen. Kunnskapen utenfra tas med tilbake til Tønsberg. I 20 år harSMART vært en plattform for sosial innovasjon med fokus på barn og unge. Gjennom SMART oppvekst, SMART ledelse og SMART arbeidsmiljø har senteret bidratt tilstyrkebaserte, inkluderende miljøer i skoler, barnehager, helse- og omsorgstjenester og andre kommunale virksomheter. SMART har også vært en viktig arena fortverrfaglig samarbeid og utvikling gjennom festivaler, kurs og samarbeid med fagfolk, ungdom og næringsliv. Dette har vært med på å bygge et inkluderendefellesskap i Tønsberg.En av de mest vellykkede satsingene har vært SMART elevråd, som har styrket ungdoms evne til å bygge trygge fellesskap på videregående skoler i Tønsberg ogomegn.</p>
```

```{=html}
<p>NAV</p>
```

```{=html}
<p>Frivillig forvaltning.       Verktøy for å hjelpe brukere til å styre sin økonomi. Ca 50 personer mottar denne tjenesten. Bruker ca 50 % stilling.       400       Dette tiltaket gjelder brukere med store utfordrimnger knyttet til å styre egen økonomi. Tiltaket betyr at NAV eksempelvis sender husleie direkte til huseier mm.Dersom tiltaket reduseres vil utgifter til øk. sosialhjelp øke</p>
```

```{=html}
<p>Vakthold       Leier vakt tjenster fra securitas.       430       Avgjørende for sikkerheten til ansatte. Alternativ til Securitas er å benytte egne ansatte</p>
```

```{=html}
<p>Godt Nok./loop front.       Bruk av loopfront. Lagret. Stilling + loopfront       900       Egen stilling, p.t. vakant</p>
```

```{=html}
<p>Min første sommer jobb og min første jobb.       Mellom 50-100 unge for hjelp til å bli kjent med arbeidslivet, forpliktelser og forventninger og få lønn.       450       Aktuelle unge er anbefatlt av skole og barnevern. Således unge i risiko sonen. Viktig å gi disse erfaringer med arbeidslivet og slik lære mulighetene som finnes der.</p>
```

```{=html}
<p>Tønsberg Læringssenter</p>
```

```{=html}
<p>Kjøp av tjenester fra andre (bransjekurs)       Vi kjøper bransjekurs som forbereder introduksjonsdeltaker til jobb innen aktuell bransje       400       Deltakere får ikke spissa bransjekurs som medfører økte sjanser til jobb etter intro. Oppgaven må løses innenfor bemanningen på TL.</p>
```

```{=html}
<p>Oppfølging av unge, kontakt med frivilligheten, TryggEst operativt team       Oppfølging av unge uten intro. Legge til rette for samarbeid med frivilligheten og delakelse i det operative teamet til TryggEst       340       Vil ikke kunne gjennomføre Flexid for unge eller bruke ressurser på unge utenfor intro. Det samme gjelder frivilligheten. Vil føre til økt utenforskap. TLs kompetansepå minoriteter vil forsvinne fra kommunens TryggEst-team.</p>
```

```{=html}
<p>Boveiledning av nybosatte       Miljøarbeider brukt på enkelte nybosatte med behov for ekstra boveiledning og støtte tidlig i bosettingsfasen       160       Ikke hjelp og veiledning i tidlig bosettingsfase. Vil føre til økt belastning for programveilederne.</p>
```

```{=html}
<p>Språkstøtte lærlinger       Salg av tjenester til opplæringskontoret for lærlinger som trenger språkstøtte for å klare fagprøven       510       Mister inntekt og også utgift brukt til opplæringen. Færre elever består fagprøven.</p>
```

```{=html}
<p>Kurs i norsk og samfunnskunnskap for betalende deltakere       bosatte i kommunen som ikke har rett til gratis norskopplæring, vil ikke få tilbud om opplæring mot b       854       Mister inntekt i tillegg til utgift brukt til lærerresseurs. Bosatte i kommunen vil ikke kjøpe opplæring ved TL. Betalende deltakere "fyller" opp gruppene med deltakeresom har rett til gratis opplæing. Vil kunne medfører dårligere tilbud til deltakere med gratis opplæring der betalende bidrar til å opprettholde opplæringstilbud</p>
```

```{=html}
<p>Kulturskole       Opplæringslova §26-1: Kommunen skal ha eit tilbod om kulturskole til barn og unge, organisert i tilknyting til skolen og kulturlivet. (Lovfestet, men ikke omfanget)       13 654       Redusert tilbud til barn og unge innenfor kulturskolen</p>
```

```{=html}
<p>KSU-Felles</p>
```

```{=html}
<p>Nasjonalparksenter       Støtte til drift av Færder nasjonalparksenter IKS (Tønsberg og Færder er eiere med 50% hver)       400       Inntekter fra lønn og regnskap er ikke med. Utgjør 250 000</p>
```

```{=html}
<p>Nasjonalparksenter       Undervisning til kommunens skoler og barnehager       100       Redusert undervisningstilbud til skolebarn i Tønsberg</p>
```

```{=html}
<p>Tilskudd DS Kysten       Tildkudd til drift av Kysten 1       1 200</p>
```

```{=html}
<p>Evangeliesenteret       Støtte til Evangeliesenterets kontaktsenter i Tønsberg       200       Arbeid rettet tiltak mot rusavhengige og kafe</p>
```

```{=html}
<p>Bakgårdsfestivalen       Gratis fesival drevet av frivillige       200       Redusert tilbud til innbyggere</p>
```

```{=html}
<p>Tønsbergfest       Tilskudd til Tønsberglivet. Erstatter Færderfestivalen       200       Redusert tilbud til innbyggere</p>
```

```{=html}
<p>Julegater       Støtte til Tønsberglivet til å pynte gater i sentrum til jul       80       Redusert tilbud og omdømme</p>
```

```{=html}
<p>KSU- Stab</p>
```

```{=html}
<p>Kirkens bymisjon       Til drift af boteam, arbeidstrening og kafe       2 776       Redusert tilbud og vil medføre økt behov i det lovpålagte</p>
```

```{=html}
<p>Ettervern - Frelsesarmeen       Ettervernstiltak for tidligere rusavhengige       500       Redusert tilbud og vil medføre økt behov i det lovpålagte</p>
```

```{=html}
<p>Plan, eiendom, og teknikk</p>
```

```{=html}
<p>Tønsberglivet       Mindre fokus på profilering av Tønsberg, samt samarbeid med Tønsberglivet.       1 000       Mindre forkus på profilering av Tønsberg, samt samarbeid med Tønsberglivet.</p>
```

```{=html}
<p>Handlingsprogram for sentrum (HPS)       Partnerbidraget fra Tønsberg i HPS       500       Redusert samhandling, færre tilatak i sentrum mister også bidrag på ca 1,1 Mill fra private</p>
```

```{=html}
<p>Reiseliv       Visit Vestfold       670       Visit Vestfold (avtalen kan sies opp etter 2025).</p>
```

```{=html}
<p>Gründerhuset       Veksthus. Ekstra ressurs for å realisere veksthus (dette er i tillegg til daglig leder)       250       Viktig for å stimulering av ny næringsvirksomhet.</p>
```

```{=html}
<p>Grunderhuset, medlemsskap       Viktig for å stimulering av ny næringsvirksomhet.       90       Redusert satsning på gründer virksomhet</p>
```

```{=html}
<p>Start i Vestfold       Samarbeid med fylket og andre Vestfoldkommuner, veileder bedrifter i oppstart + kurs       175       Redusert satsning på gründer virksomhet</p>
```

```{=html}
<p>Telemarksforskning       Analyse av attraktivitet bo-besøk-bedrift + deltakelse ikompetansenettverk       75       Mister muligheten til å få gode tall, analyse og kunnskap</p>
```

```{=html}
<p>Skjærgårdsmat       50% til skolehager og 50% til omdømmeprosjekt mat       100       Redusert tilbud</p>
```

```{=html}
<p>Div drift og mindre prosjekter</p>
```

```{=html}
<p>298       Alle andre utgifter til deltakelse konferanser, kurs, telefon, aviser, kontordrift osv.Tønsberg næringsforening - 8 - MedlemsskapMiljøfyrtårn - 10 - MedlemsskapNCCE - 30 - Norsk senter for sirkulærøkonomi. Medlemsskap, viktig for kunnskap for arbeidet med sirkulærøkonomi og RyggIMRA (velkomstbrev) - 25 - Automatisk brev til alle nye bedrifter + oversikt over nyetableringer med adresserMake nyhetsbrev - 11 - Nyhetsbrevløsning for å kunne sendes bedrifter, brukes også i medvirkning kommuneplan RyggNæringsfaglige vurderinger - - Ikke utgifter, men en tjeneste vi gjør for NAV og bruker arbeidsressurser til</p>
```

```{=html}
<p>Rygg       Utvikling og Forvaltning av kommunens interesser       1 274       Drift og inntekt er ikke medtatt</p>
```

```{=html}
<p>Befolkningsprognoser       Prognoser for å dimensjonere Helsetjenester, skole barnehage mm       200       Kunnskapsgrunnlag for å dimensjonere tjenestene</p>
```

```{=html}
<p>Levekårssoner</p>
```

```{=html}
<p>250       Kunnskapsgrunnlag for å bidra til å kunne jobbe systematisk med å utgjevne sosiale forskjellr i kommunen</p>
```

```{=html}
<p>Klimatiltak       Egenandel klimasats, klimabudsjett, div kunnskapsgrunnlag klima, klimapris       450       Utløser en rekke eksterne finsnsierte prosjekter, og følger opp politisk vedtatte bestillinger</p>
```

```{=html}
<p>Tilskudd klimatiltak lag og foreninger       Tilskuddsordning klimatiltak lag og foreninger       1 000       Bidrar til å sette foreninger i stand til å gjennomføre klimatiltak.</p>
```

```{=html}
<p>Mobilitetstiltak og planlegging</p>
```

```{=html}
<p>260       Sentral i arbeidet med mobilitetsplan og bypakka. Bidrar til å utløse mye ekstern finansiering</p>
```

```{=html}
<p>Planutarbeidelse og kunnskapsgrunnlag utover kommuneplan       Kommunedelplaner, Områdeplaner, mobilitetsplaner, prinnsipp og startegiplaner mm       800       Sentral i arbeidet med utvikling av kommunens transformasjonsområder. Bidrar til å utløse mye ekstern innsats og ekstern finansiering</p>
```

```{=html}
<p>Veiledningsmateriell       Universell utforming, verktøykasse for arkitektur, mm       250       følger opp politisk vedtatte bestillinger</p>
```

```{=html}
<p>Handlingsprogram       HP Vear, HP Sem, HP parkeringssttrategi, Kanalen som byrom, Byromstrategi       200       Sentralt for å kunne bidra til gjennomføring av politisk vedtatte planer</p>
```

```{=html}
<p>BSU Drift       Pc, tlf, reiser, kurs,kontormateriell mm       120       Trekk ut driftsmidler knyttet til lovpålagt tjenester =AVRUND(4900/8,6*(8,6-2,4);-1)</p>
```

```{=html}
<p>BSU Lønn       Ledelse. Klimarådgiver, 0.6 jurist, 1,5 prosjektleder, 2.1 planrådgiver (totalt 6,2 årsverk)       6 850       6,2 årsverk ikke lovpålagt. Trekk ut 2,4 årsverk og driftsmidler som er lovpålagt</p>
```

```{=html}
<p>Innføre markedsleie på Olsgård       Økt husleie for kunstnere på Olsgård, kan medføre mindre interesse for å leie, noe som igjen kan føre til et mindre kunstnermiljø.       200       Det kan ikke innføres markedsleie uten å oppgradere bygget. Innsparing på 1 mill er urealistisk, setter den derfor ned til samme som 2020</p>
```

```{=html}
<p>Messehall A       Bruk til kroppsøvingsfag,men er ikke fast gymsal, brukes av organisasjoner kultur/idrett. Det foreligger avtaler blant annet med Færder på A-hallen. Det er gitt spillemidler.       2 000       Leieinntekter ikke medtatt, ligger hos kultur. Finn netto</p>
```

```{=html}
<p>Messehall B       Ikke i bruk til kroppsøvingsfag, brukes av organisasjoner kultur/idrett.       700</p>
```

```{=html}
<p>Menyhallen       Kaldhall på Re, brukes til fotball, har mottatt eksterme midler.       200       Leieinntekter ikke medtatt, ligger hos kultur. Finn netto. Usikkert med kostnad kunstgress</p>
```

```{=html}
<p>Støperiet       Brukes til kulturarrangement, har mottatt eksterne midler, leieinntekter ikke medtatt       1 000       Leieinntekter hos kultur. Finn netto</p>
```

```{=html}
<p>Svømmehaller       Kommunen har fler svømmehaller enn påkrevet for svømmeundervisning, disse er kostbare i drift, men kan være en god beredskap pga Tønsberg svømmehalls alder       500       Færre lokasjoner, økt press på gjenværende hall og økt sårbarhet</p>
```

```{=html}
<p>Trafikksikkerhetsarbeid       Trafikksikkerhetsarbeid for å redusere antall skadde og drepte i kommunen. Samarbeid med Fylkeskommunen mht trafikksikkerhet. Felles planstrategi for trafikksikkerhet og arbeide med prosjekter rundt bla skoler og barnehager for å få trafikksikre løsninger.       800       Redusert satsning på trafikkssikkerhet</p>
```

```{=html}
<p>Tønsberg ishall og Maier Arena       Ikke is på Maier arena og ishallen. Dette vil medføre at lag og foreninger ikke har noe sted å trene, samt at isen på Maier arena ikke kan brukes av kommunens innbyggere. Ved stegning i mer enn 6.mnd. må det søkes kulturdepartementet grunnet tippemidler som er gitt til anlegget. For ordinære anlegg gjleder plikten til å holde oppe i 30 år. I tillegg er det en avtale med Færder som løper i 20 år med 5 år av gangen. Kan sies opp med 18 mnd. varsel før en ny 5 års periode.       3 200       Redusert tilbud</p>
```

```{=html}
<p>Tilskudd til skjøtsel av løyper og stier       Dette er utgifter til vedlikehold og tilskudd til frivillge for vedlikehold av lysløyper, turtsier, kyststi etc.       300       Redusert tilbud og omdømme</p>
```

```{=html}
<p>Klipping       klipping av alle kommunens arealer inklusiv indrettsanlegg       800       Redusert tilbud og omdømme</p>
```

```{=html}
<p>Beplantning, parkanlegg       Luking , beplanting og skjøtsel av alle kommunens grøntarealer. Inklusiv idrettsanlegg.       1 200       Redusert tilbud og omdømme</p>
```

```{=html}
<p>Badeflåter, brygger, tilbud i gjestehavner       Kostnader til badebrygger, badebøyer, badeflåter og drift av kommunale strand toaletter.       600       Populært tilbud til kommunens innbyggere.</p>
```

```{=html}
<p>Fontener       Vann og vedlikehold i kommunens fontener.       150       Redusert omdømme</p>
```

```{=html}
<p>Toaletter i byen       Offentlige toaletter i byen stenges.       100       Ved å stenge dette vil omdømme til kommunen reduseres</p>
```

```{=html}
<p>Lekeplasser       Vedlikehold og skjøtsel av offentlige lekearealer.       350       Dårligere tilbud for barn og unge.</p>
```

```{=html}
<p>Ole III/IV       Fergesambandet Husøysund/ OLE III       1 000       Redusert tilbud</p>
```

```{=html}
<p>Lærlingerordning       Læringeordning - kutte       100       Teknisk drift har to lærlinger. Dette kan nedprioriteres fremover</p>
```

```{=html}
<p>Tilrettelegging for dugnader       Utlån/tømming mm av containere til skoler, barnehager, velforeninger, FAU til dugnad på disse stedene.       100       Oppreettholder standard på våre egne områder. Faste ansatte har ikke kapasitet til å utføre disse oppgavene.</p>
```

```{=html}
<p>Lønn drift uteområder park, grønt, idrett og friluftsliv       Ledelse og fagarbeidere - 9 årsverk       6 300       Avvikling av oppgaver som ivaretas av avdelingen</p>
```

```{=html}
<p>Avtaler med idrettsforeninger       Avtaler med ulike idrettslag       500       Det leveres ulike tjenester til forskjellige klubber/foreninger utover pålagt</p>
```

```{=html}
<p>SUM</p>
```

```{=html}
<p>247 934</p>
```

```{=html}
<p>Regnskapsresultatet for 2024 gjør det nødvendig å bruke 240,1 mill. kroner av disposisjonsfondet for å gå i balanse. Sammenlignet med justert budsjett er dette en økning på 65,3 mill. kroner. I forhold til opprinnelig budsjett er det en økning på 165 mill. kroner.</p>
```

```{=html}
<p>Flere forhold peker i negativ retning i økonomiplanperioden. Både lavere skatteinntekter, økte avskrivninger og endrede regler for refusjon av ressurskrevende tjenester bidrar negativt. Samtidig leverer Tønsberg kommune tjenester på et høyere kostnadsnivå enn sammenlignbare kommuner, noe som utfordrer budsjettbalansen ytterligere.</p>
```

```{=html}
<p>Økt bruk av disposisjonsfondet tapper kommunes likviditet og kan medføre at kommunen må ta opp kassekreditlån for å kunne betale lønn til kommunens ansatte. Et kassakredittlån vil øke kravet til innsparing og omstilling ytterligere. Dersom ikke en tilstrekkelig omstilling gjennomføres i denne økonomiplanperioden, vil det kunne medføre at kommunen blir satt under administrasjon av Statsforvalteren via ROBEK-registeret.</p>
```

### Faktagrunnlag:

```{=html}
<p>Kommunens økonomiske mål er:</p>
```

```{=html}
<p>– Årlig avsetning til disposisjonsfond – langsiktig mål 1,75% i driftsresultat</p>
```

```{=html}
<p>– Netto gjeld som belaster drift skal være under 65%. av driftsinntekter</p>
```

```{=html}
<p>– Et disposisjonsfond på minimum 8 % av driftsinntektene (475 mill. kroner)</p>
```

```{=html}
<p>Kommunens netto driftsresultat endte på -3,8% når resultatet fra interkommunale selskaper Tønsberg kommune er en del av tas med. For andre år på rad har Tønsberg kommune et resultat som er betydelig svakere enn snittet for KOSTRA-gruppen og øvrige kommuner i Vestfold.</p>
```

```{=html}
<p>I februar 2024 ble prosjektet «Sunn kommuneøkonomi» igangsatt. Fase 1 ble behandlet av kommunestyret i juni 2024. I vedtatte handlingsprogram er totalt innsparingskrav i forhold til budsjett 2024 satt til 286 mill. kroner. Innsparingskravene ble fordelt på de enkelte rammeområdene, med en årlig opptrapping og full effekt i 2028.</p>
```

```{=html}
<p>Regnskapet for 2024, som ble klart i mars 2025, viser at kommunen må bruke vesentlige beløp fra disposisjonsfondet de nærmeste årene selv med innsparinger på 286 mill. kroner. Et positivt forhold ved regnskapet for 2024, er at selve driften av tjenestene har et mindreforbruk på 28 mill. kroner. Det tyder på god budsjettdisiplin og god økonomisk kontroll ute i virksomhetene.</p>
```

```{=html}
<p>De nye forutsetningene medfører at disposisjonsfondet svekkes med ytterligere 151 mill. kroner i 2025 og 83 mill. kroner i 2026. Dersom det ikke tas grep nå, vil størrelsen på disposisjonsfondet være under 200 mill. kroner ved utgangen av 2026. Det vil ikke være bærekraftig for en kommune av Tønsbergs størrelse med 60 000 innbyggere og 4 700 ansatte.</p>
```

```{=html}
<p>Statsforvalteren har merket seg det negative regnskapsresultatet for 2024, og holdt en orientering i formannskapet 31.mars og i kommunestyret 9. april. Orienteringene ble gitt for å understreke den alvorlige økonomiske situasjonen kommunen står i, og for å formidle hvordan statsforvalteren vil følge opp kommunen videre. Kun én kommune i Vestfold og Telemark har ifølge Statsforvalteren lavere netto driftsresultat enn Tønsberg i 2024.</p>
```

```{=html}
<p>KOSTRA- tall for 2024 viser at netto driftsutgifter per innbygger i Tønsberg er høyere enn i andre kommuner med tilsvarende inntektsnivå:</p>
```

```{=html}
<p>Dersom Tønsberg skulle drifte med samme netto driftsutgift som Sandefjord og Larvik, ville utgiftene vært henholdsvis 156,7 og 303,9 mill. kroner lavere per år.</p>
```

```{=html}
<p>Nivået på kommunens netto driftsutgifter per innbygger, henger ikke sammen med nivået på kommunens frie inntekter per innbygger.</p>
```

```{=html}
<p>Opprinnelig plan i henhold til «Sunn kommuneøkonomi», var å bruke 2025 til å planlegge for innsparinger fra og med 2026. Det opprinnelige innsparingskravet på 36,5 mill. kroner i 2025, skulle løses ved å reversere enkelte opptrappinger som til sammen utgjorde 5,1 mill. kroner, og gjennom to konkrete tiltak. Det ene tiltaket var en reduksjon i antall sykehjemsplasser, det andre var endret tilbudsstruktur i SFO. Disse to tiltakene utgjorde til sammen 27 mill. kroner. Resterende var knyttet til gjenstående innsparinger fra tidligere år. Tiltakene er gjennomført, men endret tilbudsstruktur i SFO ga ikke den innsparingen som var forventet. Innsparingen er isteden tatt som rammekutt på barneskolene.</p>
```

```{=html}
<p>Den økonomiske situasjonen har gjort det nødvendig å sette i gang innsparingene hurtigere enn planlagt.</p>
```

```{=html}
<p>For å kunne redusere bruken av midler fra disposisjonsfondet i 2025, er kommunedirektørens innsparingskrav til kommunalområdene for 2025 økt fra 36,5 mill. til 106,1 mill. kroner. Innsparingskravet er fordelt slik:</p>
```

```{=html}
<p>Det totale innsparingskravet på de enkelte rammeområdene for hele økonomiplanperioden framgår av tabellen under.</p>
```

```{=html}
<p>Opprinnelig innsparingskrav på 286 mill. kroner i 2028 er opprettholdt, selv om innsparingskravet er framskyndet. Ved å framskynde noe av innsparingskravet, er det mulig å redusere innsparingsbehovet senere i perioden. Tabellen ovenfor viser at man kan redusere innsparingene i 2028 med totalt 34 mill. kroner i 2028 som følge av fremskyndet innsparing, forutsatt at det totale innsparingskravet er uendret i perioden.</p>
```

```{=html}
<p>De foreslåtte tiltakene for 2025 og 2026 ligger over innsparingskravet. I stor grad skyldes dette effekter av innsparingstiltak i Mestring og helse.</p>
```

```{=html}
<p>På finansområdet ligger følgende innsparingseffekter som en forutsetning:</p>
```

```{=html}
<p>Vedlagte oversikt viser tiltak med en samlet innsparingseffekt på 106 mill. kroner i 2025, og hvilken effekt alle tiltakene som foreløpig er vurdert har utover i perioden.</p>
```

#### Kompetansekartlegging og bemanningsplanlegging

```{=html}
<p>I underkant av 70% av kommunes driftsutgifter er relatert til lønn og sosiale utgifter. Det er ikke mulig å redusere kostnadene med 286 mill. kroner innen utgangen av 2028 uten at dette medfører en reduksjon i antall ansatte. En del av reduksjonen vil kunne tas gjennom naturlig avgang, men det er ikke sikkert at dette vil være tilstrekkelig.</p>
```

```{=html}
<p>Kommunedirektøren har derfor lagt opp til at det skal utarbeides nye bemanningsplaner som er i tråd med vedtatte innsparingstiltak, og som kan sikre at organisasjonen får et bærekraftig driftsresultat.</p>
```

```{=html}
<p>Før nye bemanningsplaner utarbeides, skal det gjennomføres en oppgave- og kompetansekartlegging. Der skal det kartlegges hvilke oppgaver som løses i dag, og hvilken kompetanse som kreves for å løse oppgavene. Kartleggingen vil blant annet danne grunnlag for vurderinger knyttet til hvilke oppgaver som skal løses og ikke løses i fremtiden, hvilket nivå oppgavene skal løses på, og hvilken kompetanse det er viktig å beholde og utvikle i organisasjonen.</p>
```

```{=html}
<p>Oppgave- og kompetansekartleggingen vil utgjøre et viktig grunnlag for utarbeidelsen av nye bemanningsplaner.</p>
```

```{=html}
<p>For den enkelte vil omstillingen kunne innebære endringer, som for eksempel endret arbeidssted, stillingens innhold eller bytte av leder.</p>
```

```{=html}
<p>Derfor er involvering av ansatte, vernetjenesten og tillitsvalgtapperatet nødvendig for å sikre en så god omstillingsprosess som mulig for de ansatte. Arbeidsmiljøet og HMS-hensyn må ivaretas på en god måte i prosessen. Det er derfor nedsatt en partssammensatt arbeidsgruppe som har fått i oppgave å utarbeide en plan for omstillingsprosessen som skal ivareta ansatte, deres rettigheter og arbeidsmiljøet i prosessen.</p>
```

```{=html}
<p>Etter planen skal kommunedirektørens ledergruppe (KLG) gjennomgå kartleggingen i kommunalområdene i uke 33. Forslag til reduksjon i antall ansatte gjennomgås i KLG i uke 35.</p>
```

#### Under arbeid / nye tiltak som foreslås utredet:

```{=html}
<p>– Utredning av eiendomsskatt</p>
```

```{=html}
<p>I 2024 hadde 323 av 357 kommuner i Norge eiendomsskatt. Av disse hadde 230 kommuner eiendomsskatt i hele kommunen. Det foreligger mange tilgjengelige utredninger knyttet til eiendomsskatt. I Vestfold har Horten, Holmestrand, Larvik og Færder utredet eiendomsskatt i løpet av de siste 5 årene.</p>
```

```{=html}
<p>Å gjennomføre en overordnet beregning av hvor mye en slik inntekt kan utgjøre for Tønsberg kommune, og ikke minst hvor mye en eventuell skatt vil kunne utgjøre for kommunens innbyggere, kan gjøres uten særlig belastning av administrasjonsressurser.</p>
```

```{=html}
<p>Kommunedirektøren mener det er relevant å gjøre denne utredningen av flere årsaker. Kommunens økonomiske situasjon er krevende, og det foreligger risiko for at de økonomiske rammebetingelsene kan blir dårligere enn forutsatt. Det foreligger også usikkerhet knyttet til hvor raskt man kan få gjennomført samtlige innsparingstiltak som er nødvendig. En annen årsak til at man bør utrede eiendomsskatt, handler om Tønsberg kommunes evne til å bygge en kommune for fremtiden, samt evnen til å gjennomføre større endringer knyttet til struktur og utvikling av byen i tråd med kommuneplanens samfunnsdel.</p>
```

```{=html}
<p>Selv om man lykkes med de gjennomførte omstillingstiltakene, vil det ta tid å bygge opp en robust kommune som tåler større investeringer. Som et ledd i «Sunn kommuneøkonomi» settes nye investeringer på vent for å skjerme driften for ytterligere belastninger knyttet til renter og avdrag. Samtidig står kommunen ovenfor en tid som krever store investeringer for å kunne håndtere endringer i demografi og klima.</p>
```

```{=html}
<p>Inntekter fra eiendomsskatt vil kunne skaffe Tønsberg kommune et tilstrekkelig handlingsrom for å gjennomføre de investeringer som trengs for å nå målene i kommuneplanens samfunnsdel raskere. Dersom nye investeringer igangsettes før tilstrekkelig økonomisk handlingsrom er opparbeidet, vil det kunne medføre behov for ytterligere omstilling og reduksjon i tjenestetilbud.</p>
```

```{=html}
<p>Mange frykter at en innføring av eiendomsskatt vil kunne bli en sovepute for nødvendig omstilling og effektivisering. Det er imidlertid flere kommuner som kan vise til å være blant Norges mest effektive kommuner, som samtidig har inntekter fra eiendomsskatt. Disse kommunene kjennetegnes ved å ha solide disposisjonsfond, og har en stor grad av økonomisk handlefrihet og politisk handlingsrom.</p>
```

```{=html}
<p>En utredning om innføring av eiendomsskatt vil kunne legges frem for politisk nivå i september 2025 som en orienteringssak.</p>
```

```{=html}
<p>– Gjennomgang av modell for refusjon ressurskrevende tjenester</p>
```

```{=html}
<p>Nye regler for refusjon for ressurskrevende tjenester ga kommunen en inntektssvikt i 2024. Samtidig har Tønsberg en forholdsmessig lav andel i refusjon sammenlignet med andre kommuner. Tønsberg kommune har også en lav andel ressurskrevende brukere i forhold til innbyggertall i Vestfold. En større gjennomgang av hvordan ordningen praktiseres forslås for å kvalitetssikre at kommunen får de inntektene kommunen har krav på. Dette innebærer å se på vedtaksformuleringer og å gjennomgå forutsetninger som benyttes i dagens modell for utarbeidelse av refusjonskrav.</p>
```

```{=html}
<p>– Arealeffektivisering, salg og utnyttelse av kommunale eiendommer.</p>
```

```{=html}
<p>Kommunen har en stor eiendomsmasse og er lokalisert på mange ulike steder i kommunen. Det er behov for en større gjennomgang for å finne ut hvor det er mulig å kutte utgifter, vurdere eksisterende leiekontrakter og hvordan vi kan utnytte kontorlokaler på en bedre måte. I dette arbeidet vil det kunne være behov for å leie inn noe ekstern bistand. Salg av eiendommer legges fram som egen sak i juni 2025.</p>
```

```{=html}
<p>– Dimensjonering av administrative ressurser og eventuelt justering av administrativ organisering</p>
```

```{=html}
<p>Tønsberg kommune er en stor organisasjon med ca. 4 700 ansatte. Kommunens administrative organisering er kontinuerlig oppe til vurdering, både når behov endrer seg og når lederstillinger blir ledige. Antall kommunalsjefer er for eksempel redusert fra 8 til 6 siden sammenslåingen av Re og Tønsberg i 2020.</p>
```

```{=html}
<p>Kommunen har i dag en tradisjonell organisering der de administrative tjenestene er inndelt i kommunalområder med hver sin kommunalsjef. I tillegg er drifts- og utviklingsrelaterte stabsoppgaver i stor grad samlet i to sentrale stabsområder, Økonomi og virksomhetsstyring og Organisasjon og utvikling. Tjenester som naturlig hører sammen, er i stor grad samorganiserte. Innenfor kommunalområdene er tjenestene inndelt i til sammen 64 virksomheter som har delegert ansvar for fag, økonomi og personell innenfor sitt ansvarsområde. Virksomhetene er av ulik størrelse både i økonomi og antall ansatte.</p>
```

```{=html}
<p>Kommunedirektøren ønsker å gjøre en vurdering av dimensjonering av administrative ressurser i sentrale staber og stabsfunksjoner hos kommunalsjefene. I gjennomgangen vil det være naturlig å sammenligne seg med andre kommuner av omtrent samme størrelse som Tønsberg. Kommunen er avhengig av å ha en oppdatert, formålstjenlig og effektiv organisering av de administrative ressursene. Tønsberg kommune må sikre at organisasjonen kan levere på ulike målsetninger, både i daglig tjeneste og drift, men også i arbeidet med utvikling og omstilling framover. Gjennomgangen vil også innbefatte flere tiltak som kunne stått på listen over «ikke lovpålagte tjenester», men kommunedirektøren velger å se dette i en helhet og ta det med i saken som legges frem i forbindelse med behandling av handlingsprogram 2026-29.</p>
```

#### Liste over «ikke lovpålagte» tjenester

```{=html}
<p>Det er utarbeidet en liste over «ikke lovpålagte tjenester» per mai 2025. Lista følger som vedlegg til saken. Begrepet «ikke lovpålagte tjenester» er utfordrende. Det er lite kommunen driver med som ikke har sitt opphav i lov, på ett eller annet nivå. Av det gjenværende er det meste enten nødvendige støttefunksjoner for å kunne oppfylle de oppgavene som loven nevner, avtaleforpliktelser kommunen har påtatt seg, eller aktiviteter som er nødvendige for å ha et bærekraftig lokalsamfunn på sikt.</p>
```

```{=html}
<p>Det er store forskjeller i hvordan ulike områder er lovregulert. I noen sektorer, slik som opplæring, har storting og regjering til en viss grad valgt å detaljstyre ressursbruken. På andre områder, slik som kultursektoren, har storting og regjering valgt en mer overordnet tilnærming, med overordnede mål-og funksjonskrav.</p>
```

```{=html}
<p>Staten følger også opp de ulike tjenestene i kommunene på ulik måte. Innen helsevern, sosialsaker, arealforvaltning og ulike sider ved opplæringen gjøres dette gjennom mer inngripende tiltak, som for eksempel tilsyn.</p>
```

```{=html}
<p>I mange tilfeller er de «ikke lovpålagte tjenestene» oppgaver og tilbud til innbyggerne som ligger langt ned i Tønsberg-trappa. I mange tilfeller avlaster og supplerer de «ikke lovpålagte» tjenestene de lovpålagte tjenestene. Dersom de fjernes eller reduseres, vil det kunne føre til økt press på de lovpålagte tjeneste. Det er derfor viktig at det foretas en analyse og konsekvensvurdering av hvordan tjenestene henger sammen og hvordan de påvirkes ved en eventuell reduksjon eller bortfall. Lista inneholder en kort beskrivelse av tjenesten, netto utgift i budsjett 2025 og en beskrivelse av mulig økonomisk effekt ved reduksjon/bortfall, samt en kort beskrivelse av direkte og indirekte konsekvenser.</p>
```

```{=html}
<p>Listen over «ikke lovpålagte tjenester» er ikke uttømmende. En revidert utgave vil bli presentert i forbindelse med fremleggelsen av budsjett og økonomiplan 2026-2029.</p>
```

```{=html}
<p>Interne stabstjenester og funksjoner er ikke inkludert i lista. Disse bli vurdert i egen sak om administrative organisering og dimensjonering av administrative ressurser.</p>
```

#### Lånegarantier:

```{=html}
<p>Tønsberg kommune har over tid hatt en praksis med å innvilge lånegarantier til idrettslag og andre organisasjoner når de har foretatt utbygginger av anlegg med mer. I tillegg har tidligere Re kommune innvilget lånegaranti til to private barnehager. Per utgangen av 2024 utgjorde lånegarantiene samlet 154 mill. kroner. Alle garantier er gitt som simpel kommunal lånegaranti, med unntak av garanti stilt ovenfor Stiftelsen Flint idrettshall. Lånegarantier må godkjennes av kommunestyret. Er garantien på over 7 mill. Kroner, må saken også behandles av Statsforvalteren. Det ligger nå to konkrete saker til behandling, der kommunen risikerer å måtte innfri lånegarantien. Dette gjelder Rema 100 hallen (Flinthallen) og Tønsberg Kajakk-klubb. Siste tids utvikling viser at lånegaranti utgjør en risiko for kommunen, som i verste fall vil medføre ytterligere behov for kutt i tjenestetilbudet kommunen leverer. Kommunedirektøren foreslår derfor at ordningen vurderes på nytt og resultatet av dette arbeidet legges fram som egen sak høsten 2025.</p>
```

#### Gjennomgang av planlagte investeringer

```{=html}
<p>I kommunens perioderapport foreslås en forskyvning/utsettelse av vedtatte investeringsrammer tilsvarende 131 mill. kroner som følge av forsinket fremdrift eller oppstart. Administrasjonen arbeider videre med en gjennomgang av alle planlagte investeringer og presenterer en revidert fremdriftsplan for disse i en egen sak høsten 2025. I denne saken vil man synliggjøre konsekvensvurderinger for de enkelte prosjektene med hensyn til en utsettelse.</p>
```

```{=html}
<p>I k-sak 206/24 er det vedtatt at det skal gjøres klimavurdering tilknyttet alle planlagte investeringer i planperioden:</p>
```

```{=html}
<p>«I forbindelse med budsjett 2026 bes kommunedirektøren videreutvikle klimabudsjettet til å synliggjøre klimaeffekt (negativ og positiv) av planlagte investeringer i planperioden.»</p>
```

```{=html}
<p>Administrasjonen vil arbeide for at også klimaeffekter av planlagte investeringer og eventuelle utsettelser synliggjøres.</p>
```

```{=html}
<p>Oversikt over pågående investeringer i 2025 følger som vedlegg til perioderapporteringen som kommer til behandling i juni.</p>
```

```{=html}
<p>Følgende saker legges fram som egne saker:</p>
```

```{=html}
<p>– Ytterligere reduksjon av sykehjemsplasser – orienteringssak</p>
```

```{=html}
<p>– Flytting av Øyeblikkelig hjelp døgnplasser – orienteringssak</p>
```

```{=html}
<p>– Sykefraværsoppfølging i Mestring og helse</p>
```

### Rettslig grunnlag

```{=html}
<p>Kommunelovens § 14-1setter noen grunnleggende krav til økonomiforvaltningen;</p>
```

```{=html}
<p>– Kommunen skal forvalte økonomien slik at den økonomiske handleevnen blir ivaretatt over tid.</p>
```

```{=html}
<p>– Kommunen skal utarbeide samordnete og realistiske planer for egen virksomhet og økonomi og for lokalsamfunnets eller regionens utvikling.</p>
```

```{=html}
<p>– Kommunen skal forvalte finansielle midler og gjeld på en måte som ikke innebærer vesentlig finansiell risiko, blant annet slik at betalingsforpliktelser kan innfris ved forfall.</p>
```

```{=html}
<p>Videre skal økonomiplanen og årsbudsjettet settes opp i balanse og være realistiske, fullstendige og oversiktlige, jfr. kommunelovens §14-4.</p>
```

```{=html}
<p>Økonomiforvaltningen skal sikre at kommunens innbyggere får de tjenester de har krav på etter lov, forskrift med mer.</p>
```

### Forholdet til kommuneplanen

```{=html}
<p>Hele kommuneplanen har som forutsetning at kommunen har økonomi til å løse samfunnsoppdraget og er i stand til å levere gode tjenester, drive aktiv samfunnsutvikling, sikre og utvikle lokaldemokratiet og å forvalte lover og forskrifter.</p>
```

```{=html}
<p>Hovedmålet under Kommunen som organisasjon er:</p>
```

```{=html}
<p>Tønsberg kommune er en attraktiv arbeidsgiver hvor ansatte har kompetanse som samsvarer med de oppgaver kommunen skal løse.</p>
```

### Vurderinger:

```{=html}
<p>Tønsberg kommunes regnskapsresultater har medført en reduksjon av kommunens disposisjonsfond på 358 mill. kroner. Gjenværende midler på kommunens disposisjonsfond per 31.12.2024 utgjør 432 mill. Kroner, og det er i gjeldende budsjett og økonomiplan vedtatt ytterligere tæring på fond de neste to årene. Oppdaterte budsjettprognoser tilsier reduserte inntekter og økte kostnader utover vedtatt budsjett.</p>
```

```{=html}
<p>Dersom det ikke tas grep nå, vil størrelsen på disposisjonsfondet være 280 mill. kroner ved utgangen av 2025, og under 200 mill. kroner ved utgangen av 2026. Dette er ikke en tilstrekkelig bufferkapital mot uforutsette hendelser. Tønsberg kommune har vedtatt at størrelsen på kommunens disposisjonsfond bør være minimum 8% av brutto driftsinntekter. Det tilsvarer 475 mill. kroner med brutto driftsinntekter tilsvarende 5,9 mrd.</p>
```

```{=html}
<p>Administrasjonen jobber langs flere spor for å bedre økonomien på kort sikt og lang sikt, slik at bruken av disposisjonsfondet i 2025 og 2026 holdes så lavt som mulig. Dette gjøres blant annet gjennom ulike effektiviseringstiltak, flate rammekutt, redusert servicenivå og tjenestetilbud, reduserte tilskudd, økning av inntekter og endring av struktur og volum på tjenestene. Konsekvenser av foreslåtte tiltak og rammejusteringer er vurdert i vedlagte tiltakskort. Det er ikke tiltakskort for mindre justeringer og tiltak.</p>
```

#### Nærmere om grepene for framskyndet innsparing i 2025:

```{=html}
<p>Kommunedirektøren har også iverksatt midlertidig stopp for ulike arrangementer og tiltak for ansatte der utgiftene har vært belastet kommunen.</p>
```

```{=html}
<p>Øvrige grep som iverksettes fra og med mai 2025, er at kun høyst nødvendige innkjøp og ansettelser foretas videre i 2025. Innkjøp må godkjennes av virksomhetsleder, og ansettelser må godkjennes av kommunalsjef.</p>
```

```{=html}
<p>Kommunedirektøren har ikke foreslått endringer som berører politisk struktur og antall medlemmer, og vurderer at det er kommunestyret som eventuelt innleder et slikt arbeid.</p>
```

#### Redusere eksisterende rammer basert på mindreforbruk i driften i 2024 – totalt 25 mill. kroner

```{=html}
<p>Basert på mindreforbruk over tid, foreslås det at rammene for kommunalområdet kultur og samfunnsutvikling reduseres med 20 mill. kroner. Dette gjelder NAV og Tønsberg læringssenter. Tiltaket innebærer usikkerhet, og forutsetter vedtatt nivå på bosetting av flyktninger for 2025. Utviklingen må følges nøye utover høsten og eventuell justering vurderes i perioderapport 2.</p>
```

```{=html}
<p>I statsbudsjett for 2024 var det lagt til grunn en reduksjon i stønadsperioden for kontantstøtte fra 1. august 2024, som ville føre til en økt etterspørsel etter barnehageplass. Ved en feil ble ikke helårsvirkning av denne endringen kompensert for i forslag til statsbudsjett for 2025. Tønsberg ble kompensert for dette med 2,064 mill. kroner. Beløpet ble tilført oppvekst og læring. Barn og unge har over tid hatt et mindreforbruk som knyttes til vakante stillinger. Mindreforbruket i 2023 og 2024 var henholdsvis 2,9 og 2,4 mil. kroner. Basert på dette, foreslås at rammene for oppvekst og læring reduseres med 5 mill. kroner i 2025.</p>
```

#### Ansatte arrangementer, kaffetrekk - 1,7 mill. kroner

```{=html}
<p>Kommunedirektøren har iverksatt en reduksjon av flere velferdstiltak overfor ansatte. Det er innført midlertidig stopp på arrangementer for ansatte der utgiftene belastes kommunen, som for eksempel sommer- og juleavslutninger, og sommer- og julearrangement for alle ansatte på Slottsfjell og i Stoltenbergparken. Det vil ikke bli kjøpt inn julegaver til ansatte i 2025, og det innføres stopp i bevertning og møtemat.</p>
```

```{=html}
<p>Ansatte har også hatt gratis kaffe og te. Kommunedirektøren har besluttet å innføre en egenandel, og ordningen trådte i kraft 01.05.2025. Egenandelen er på kr. 50,-/mnd. for ansatte med 50-100% stilling. For ansatte under 50% er egenandelen satt til kr. 25,-/mnd. Det er beregnet en inntekt i 2025 på 1,5 mill. kroner, stigende til 2,3 mill. kroner på helårsbasis. Beregningen er basert på at 80 % av de ansatte går inn på ordningen med månedlig trekk.</p>
```

#### Framskynde innsparingskravet per rammeområde – totalt 33,1 mill. kroner

```{=html}
<p>Av disse er 23,1 mill. kroner fordelt på kommunalområdene etter andel lønns- og driftsutgifter ekskl. selvkost. 10 mill. kroner er fordelt på kommunalområdene etter en vurdering av historisk merinntekt i form av sykepengerefusjon for 2023 og 2024.</p>
```

```{=html}
<p>Kommunen står foran en krevende oppgave, og tida er knapp. Skal kommunen lykkes, må alle tiltak og satsinger vurderes på nytt, sett i lys av den forverrede økonomiske situasjonen.</p>
```

```{=html}
<p>Tønsberg-trappa er utviklet som et nytt verktøy som skal bidra til at både politikere og administrasjon lykkes med å prioritere riktig. Målet er å lykkes bedre med forebygging og tidlig innsats, og Tønsberg-trappa skal bidra til at vi klarer å skape mest mulig velferd innenfor de økonomiske rammene vi har. Det er ikke et innsparingsverktøy, men et verktøy som skal hjelpe til å bruke de ressursene vi har på best mulig måte.</p>
```

```{=html}
<p>Omfordelingen av ressurser må skje over tid, slik at Tønsberg-trappa på sikt blir det verktøyet det er tenkt. Slik den økonomiske situasjonen er nå, må tiltak på alle nivåer i trappa vurderes, inkludert tiltak på de laveste trinnene.</p>
```

#### Innsparingspotensial framover

```{=html}
<p>Når vi sammenligner Tønsberg med andre kommuner, ser vi at det største innsparingspotensialet for Tønsberg ligger innenfor de største sektorene - altså mestring og helse og oppvekst og læring. Dette bekreftes i KOSTRA-tallene for 2024.</p>
```

```{=html}
<p>Dekningsgrad:</p>
```

```{=html}
<p>Det dyreste omsorgstilbudet en kommune har, er en ordinær sykehjemsplass med en netto utgift på 1,4 mill. kroner per år. En omsorgsplass har til sammenligning en netto utgift på 0,9 mill. kroner per år. Tønsberg kommunes sykehjemsplasser ligger lavt på sammenligninger av pris per plass. Det vil si at kommunen drifter sine sykehjemsplasser effektivt, men har flere plasser i forhold til befolkningen enn øvrige kommuner i Vestfold og snittet i vår KOSTRA-gruppe.</p>
```

```{=html}
<p>Gjeldende vedtak om dekningsgrad for heldøgnsbemannede omsorgsplasser er opptil 18 % og ikke lavere enn 14 %, jfr. k-sak 112/24. Dekningsgrad er et enkelt matematisk uttrykk for antallet døgnbemannede plasser delt på antallet innbyggere over 80 år i kommunen.</p>
```

```{=html}
<p>Med de forslagene til endringer som ligger i «Sunn kommuneøkonomi», vil dekningsgraden i Tønsberg være i underkant av 17 % i 2025. Dette innebærer drift av 517 plasser. Selv med denne reduksjonen i antall sykehjemsplasser i 2025, vil Tønsberg kommune fortsatt ha en betydelig høyere dekningsgrad enn kommunene vi sammenligner oss med.</p>
```

```{=html}
<p>Sammenlignbare kommuner som Sandefjord og Larvik har i sine planer lagt til grunn en dekningsgrad på 13 %. Legger Tønsberg seg på samme dekningsgrad som nabokommunene, vil det utgjøre et betydelig økonomisk potensial for innsparing for kommunen.</p>
```

### Konsekvens for oppnåelse av FNs bærekraftmål:

```{=html}
<p>FNs bærekraftmål har en overbygning hvor det skal finnes løsninger over tid som sørger for at samfunnsutviklingen ivaretar økonomisk, sosial og klima- og miljømessig bærekraft.</p>
```

```{=html}
<p>Alle disse tre dimensjonen må være ivaretatt for å innfri bærekraftig utvikling.</p>
```

```{=html}
<p>I denne saken er økonomisk bærekraft vært tyngst vektlagt, da kommunen er i en situasjon hvor vi uten tiltak vil kunne miste evnen til å ivareta vårt samfunnsoppdrag på en tilfredsstillende måte. Uten en bærekraftig økonomi, vil vi ha utfordringer med å innfri innenfor sosial og klima- og miljømessig bærekraft.</p>
```

```{=html}
<p>Nedskjæringer og aktivitetskutt er som oftest ensbetydende med redusert utslipp og redusert beslaglegning av natur. Dette er ikke en sammenheng som alltid vil være gjeldende. I de kuttene som anbefales for 2025, er det vurdert å være en svak positiv effekt på klimautslipp, og nøytral effekt på miljø. Over tid, med redusert bemanning som eksempelvis ikke erstatning med vikar ved sykdom og permisjoner, kan dette sette kommunen i en situasjon med redusert kapasitet til å jobbe systematisk med klima- og miljøtiltak.</p>
```

```{=html}
<p>Innen sosial bærekraft er bildet noe mer blandet, og de mest sentrale effektene er beskrevet i tiltakskortene. Det vurderes at Tønsberg kommune generelt har gode tjenester og leverer på et høyt tjenestenivå. De forslag som gjelder 2025 anses ikke å medføre at kommunen leverer uforsvarlige tjenester. Det vil likevel, for enkelte som blir berørt, kunne oppleves som en negativ utvikling innen sosial bærekraft.</p>
```

### Effekt for klima:

```{=html}
<p>I de kuttene som anbefales for 2025 er det vurdert å være en svak positiv effekt på klimautslipp, da aktivitetsnivået reduseres.</p>
```

### Konsekvenser for barn og unge

```{=html}
<p>Vurdering av konsekvenser framgår av tiltakskortene som følger som vedlegg til saken.</p>
```

### Alternative løsninger

```{=html}
<p>Innsparingskravet som ligger i vedtatte handlingsprogram videreføres uten fremskyndelse av ytterligere innsparinger i 2025.</p>
```

### Økonomiske konsekvenser

```{=html}
<p>Tas det tilstrekkelige grep nå, vil kommunen kunne få kontroll på økonomien og ha mulighet til å bygge opp størrelsen av disposisjonsfondet mot slutten av økonomiplanperioden. Totalt er innsparingene i 2025 beregnet til i 106 mill. kroner. Dette er over innsparingskravet. Det gjenstår fortsatt udekkede innsparingskrav i 2027 og 2028, som vil bli spesifisert i behandlingen av handlingsprogram for 2026-29.</p>
```

### Konklusjon

```{=html}
<p>Kommunedirektøren anbefaler at nivået på innsparingstiltak i 2025 gjennomføres i tråd med vedlegg til denne saken. Andre innsparingstiltak, som skal ha full effekt i 2026, må legges fram for politisk behandling høsten 2025. Resterende tiltak legges inn i kommunedirektørens forslag til handlingsprogram for 2026-29.</p>
```

```{=html}
<p>Kommunen står foran et betydelig innsparingsprogram. Dersom vi lykkes med den planlagte omstillingen, vil kommunen stå i en bedre økonomisk situasjon ved utgangen av 2028.</p>
```

```{=html}
<p>Samtidig som vi gjennomfører omstillingen, skal vi bygge fremtidens kommune. Dette må gjøres gjennom dialog og samhandling mellom alle aktører. En forutsetning er at kommunens ansatte har riktig kompetanse. Prosessene om kompetansekartlegging og bemanningsplaner blir derfor meget viktige.</p>
```

```{=html}
<p>Sammen skal vi skape en nytenkende, trygg og bærekraftig kommune.</p>
```

### Videre behandling:

```{=html}
<p>Sluttbehandles i kommunestyret 18.06.25</p>
```

```{=html}
<p>Tønsberg, den 21. mai 2025</p>
```

```{=html}
<p>Mette Vikan Andersen kommunedirektør</p>
```

```{=html}
<p>Kristian Holberg Lægreid kommunalsjef</p>
```

::::

```{=html}
<div class="post-share">
  <span>Del:</span>
  <a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fsstraume97.github.io%2Fhjem%2Fblogg%2Fsunn-kommuneokonomi-fase-2-tonsberg-kommune%2F" target="_blank" rel="noopener">Facebook</a>
  <a href="https://twitter.com/intent/tweet?text=%22Sunn%22%20kommune%C3%B8konomi%20fase%202%20-%20T%C3%B8nsberg%20kommune&url=https%3A%2F%2Fsstraume97.github.io%2Fhjem%2Fblogg%2Fsunn-kommuneokonomi-fase-2-tonsberg-kommune%2F" target="_blank" rel="noopener">X</a>
  <a href="mailto:?subject=%22Sunn%22%20kommune%C3%B8konomi%20fase%202%20-%20T%C3%B8nsberg%20kommune&body=https%3A%2F%2Fsstraume97.github.io%2Fhjem%2Fblogg%2Fsunn-kommuneokonomi-fase-2-tonsberg-kommune%2F">E-post</a>
  <button type="button" onclick="navigator.clipboard.writeText('https://sstraume97.github.io/hjem/blogg/sunn-kommuneokonomi-fase-2-tonsberg-kommune/');this.textContent='Lenke kopiert!'">Kopier lenke</button>
</div>
```
